const fs=require('node:fs');
const source=fs.readFileSync('tests/serials.test.cjs','utf8');
const bootstrap=source.slice(0,source.indexOf('\n(async()=>{'));
eval(bootstrap+String.raw`
(async()=>{
 await crmRoute.GET(new Request('https://crm.test/api/crm'));
 for(const role of ['agent','operator','manager','director'])await post(crmRoute,{action:'member',data:{email:role+'@example.test',name:role,role,active:true}});
 const wh=(await stock('create_warehouse',{name:'Test'}))[1].id;
 const item=(await stock('create_item',{code:'TEST',name:'Phone'}))[1].id;
 await stock('record_purchase',{item_id:item,warehouse_id:wh,qty:2,unit_cost:100});
 const as=role=>{user={userId:role,email:role+'@example.test',displayName:role};};
 const sale={item_id:item,warehouse_id:wh,qty:1,unit_price:200};
 const count=table=>sqlite.prepare('SELECT COUNT(*) n FROM '+table).get().n;
 const qty=()=>sqlite.prepare('SELECT SUM(qty_delta) n FROM inventory_stock_moves').get().n;
 as('operator');const requestId=crypto.randomUUID();
 const send=()=>post(stockRoute,{action:'record_sale',data:sale,request_id:requestId});
 let [status,pending]=await json(await send());assert.equal(status,200);assert.equal(pending.status,'pending');
 assert.equal(count('inventory_sales'),0);assert.equal(qty(),2);assert.equal(count('inventory_units'),0);
 assert.equal((await json(await send()))[1].id,pending.id);assert.equal(count('direct_sale_requests'),1);
 assert.equal((await stock('approve_sale',{},pending.id))[0],403);
 as('agent');assert.equal((await json(await stockRoute.GET(new Request('https://crm.test/api/inventory?view=sale_requests'))))[1].count,0);
 let [,other]=await stock('record_sale',sale);assert.equal(other.status,'pending');assert.equal(qty(),2);
 as('manager');assert.equal((await json(await stockRoute.GET(new Request('https://crm.test/api/inventory?view=sale_requests'))))[1].count,2);
 access.member=async()=>sqlite.prepare('SELECT * FROM members WHERE email=?').get(user.email);
 const approvals=await Promise.all([stock('approve_sale',{},pending.id),stock('approve_sale',{},pending.id)]);
 assert.deepEqual(approvals.map(r=>r[0]).sort(),[200,409]);assert.equal(qty(),1);assert.equal(count('inventory_sales'),1);
 assert.equal(sqlite.prepare('SELECT seller FROM inventory_sales').get().seller,'operator@example.test');
 assert.equal(sqlite.prepare('SELECT reviewed_by FROM direct_sale_requests WHERE id=?').get(pending.id).reviewed_by,'manager@example.test');
 as('director');assert.equal((await stock('reject_sale',{},other.id))[0],400);
 assert.equal((await stock('reject_sale',{note:'Incorrect details'},other.id))[0],200);assert.equal(qty(),1);
 assert.equal((await stock('approve_sale',{},other.id))[0],409);
 as('operator');const [,short]=await stock('record_sale',sale);
 as('manager');await stock('record_sale',sale);assert.equal(qty(),0);
 assert.equal((await stock('approve_sale',{},short.id))[0],409);
 assert.equal(sqlite.prepare('SELECT status FROM direct_sale_requests WHERE id=?').get(short.id).status,'pending');
 assert.equal(qty(),0);assert.equal(count('inventory_sales'),2);
 console.log('PASS: operator/agent pending only, no stock/serial/sale before approval, own-list scope, manager approval race, director rejection, seller attribution, duplicate submission, insufficient-stock rollback.');
})().catch(e=>{console.error(e);process.exitCode=1;});
`);
