import assert from 'node:assert/strict';
import {createClient} from '@libsql/client';
import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {planBalance} from '../scripts/inventory-sheet-plan.mjs';
import {applyBalance,inventorySnapshot} from '../scripts/sync-inventory-sheet.mjs';
import {unionSpreadsheetId} from '../scripts/inventory-sheet-source.mjs';
const folder=await mkdtemp(join(tmpdir(),'antmall-sheet-test-'));
const db=createClient({url:'file:'+join(folder,'test.db').replaceAll('\\','/')});
try{
 for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await db.executeMultiple(await readFile('drizzle/'+f,'utf8'));
 await db.execute("INSERT INTO inventory_items(id,code,name,created_by,created_at,updated_at) VALUES('i','TEST','Product','test','now','now')");
 await db.execute("INSERT INTO inventory_warehouses(id,name,created_at) VALUES('w','Сонсголон агуулах','now')");
 await db.execute("INSERT INTO inventory_stock_moves(id,item_id,warehouse_id,kind,qty_delta,value_cents,actor,created_at) VALUES('m','i','w','opening',3,900,'test','now')");
 const h=Array(24).fill('');for(const [i,v]of [[1,'Код'],[3,'Нэр'],[6,'Imei'],[7,'Агуулах'],[15,'Тоо ширхэг c2'],[16,'Нэгжийн үнэ c2']])h[i]=v;
 const row=Array(24).fill('');Object.assign(row,{1:'TEST',3:'Product',7:'Урд агуулах',15:1,16:99});
 const source={spreadsheetId:'test',readAt:new Date().toISOString(),values:[[],h,row]};
 let snapshot=await inventorySnapshot(db),p=planBalance(source,snapshot);
 assert.equal(p.changes[0].delta,-2);assert.equal(p.changes[0].value_cents,-600);
 const union=structuredClone(source);union.spreadsheetId=unionSpreadsheetId;union.values[0][17]=46285;union.values[2][7]='Арын агуулах';
 const unionCrm=structuredClone(snapshot);unionCrm.warehouses[0].name='Union';unionCrm.balances[0].last_movement_at='2026-09-19T16:00:00.000Z';
 assert.equal(planBalance(union,unionCrm).changes[0].warehouse,'Union');
 unionCrm.balances[0].last_movement_at='2026-09-21T00:00:00.000Z';assert.equal(planBalance(union,unionCrm).changes.length,0);
 union.values[2][7]='Урд агуулах';assert.equal(planBalance(union,unionCrm).targets.length,0);
 const wrong=structuredClone(source);wrong.values[2][6]='123';assert.equal(planBalance(wrong,snapshot).changes.length,0);
 const dup=structuredClone(source);dup.values.push(row);assert.equal(planBalance(dup,snapshot).issues.length,2);
 const blank=structuredClone(source);blank.values[2][15]='';assert.equal(planBalance(blank,snapshot).issues.length,1);
 await assert.rejects(applyBalance(db,source,'wrong'),/changed since preview/);
 await assert.rejects(applyBalance(db,source,p.digest,'wrong-plan'),/Inventory changed since preview/);
 assert.equal((await inventorySnapshot(db)).balances[0].qty,3);
 const result=await applyBalance(db,source,p.digest);assert.equal(result.changed,1);
 snapshot=await inventorySnapshot(db);assert.equal(snapshot.balances[0].qty,1);assert.equal(snapshot.balances[0].value_cents,300);
 assert.equal((await applyBalance(db,source,p.digest)).state,'already_applied');
 await db.execute("INSERT INTO inventory_stock_moves(id,item_id,warehouse_id,kind,qty_delta,value_cents,actor,created_at) VALUES('sale','i','w','sale',-1,-300,'test','now')");
 assert.equal((await applyBalance(db,source,p.digest)).state,'already_applied');assert.equal((await inventorySnapshot(db)).balances[0].qty,0);
 const next=structuredClone(source);next.values[2][15]=2;const nextPlan=planBalance(next,await inventorySnapshot(db));assert.equal(nextPlan.changes[0].value_cents,19800);
 console.log('PASS: warehouse mapping, exact identity, invalid/duplicate rejection, proportional valuation, atomic digest rejection, apply verification, repeat snapshot and post-sale replay protection.');
}finally{db.close();await rm(folder,{recursive:true,force:true,maxRetries:10,retryDelay:200}).catch(e=>{if(e.code!=='EBUSY')throw e;});}
