import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {priceKey,pricePlan} from '../scripts/sync-product-prices.mjs';
const mod={exports:{}};
new Function('module','exports',ts.transpileModule(readFileSync('lib/inventory-pricing.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(mod,mod.exports);
const {salePrice}=mod.exports;
assert.equal(salePrice({sale_price:100,cash_price:80},'cash'),80);
assert.equal(salePrice({sale_price:100,cash_price:80},'credit'),100);
for(const cash_price of [undefined,null,101,-1,NaN])assert.equal(salePrice({sale_price:100,cash_price},'cash'),100);
assert.equal(salePrice({sale_price:100,cash_price:0},'cash'),0);
assert.equal(priceKey('IPHONE 17 PRO MAX 256GB 4X/A'),priceKey('iPhone 17 ProMax 256GB'));
assert.notEqual(priceKey('iPhone 17 Pro 256GB'),priceKey('iPhone 17 Pro 512GB'));
assert.notEqual(priceKey('IPAD WIFI'),priceKey('IPAD WIFI CELL'));
assert.equal(priceKey('IWATCH SER 11 42MM'),priceKey('APPLE WATCH S11','42MM'));
assert.notEqual(priceKey('APPLE WATCH S11','42MM'),priceKey('APPLE WATCH S11','46MM'));
const item={id:'1',code:'X',name:'IPHONE 16 128GB LL/A',capacity:'128GB',sale_price:90,cash_price:null};
const row={row:2,name:'IPHONE 16 128GB',model:'128GB',base:100,cash:80,issues:[]};
assert.equal(pricePlan([item],{rows:[row]}).changes[0].cash,80);
assert.equal(pricePlan([{...item,name:item.name+' USED'}],{rows:[row]}).changes.length,0);
assert.equal(pricePlan([item],{rows:[{...row,issues:['special terms']}]}).changes.length,0);
assert.equal(pricePlan([item],{rows:[row,{...row,row:3,cash:70}]}).changes.length,0);
assert.equal(pricePlan([{...item,sale_price:100,cash_price:80}],{rows:[row]}).unchanged.length,1);
console.log('PASS: cash/credit price selection, missing discount fallback, model capacity, watch size, used goods, conflicting/conditional prices and repeat-run idempotency.');
