const fs=require('node:fs');
const source=fs.readFileSync('tests/serials.test.cjs','utf8');
eval(source.slice(0,source.indexOf('\n(async()=>{'))+String.raw`
(async()=>{
 await crmRoute.GET(new Request('https://crm.test/api/crm'));
 for(const role of ['operator','manager','director'])await post(crmRoute,{action:'member',data:{email:role+'@example.test',name:role,role,active:true}});
 const as=role=>{user={userId:role,email:role+'@example.test',displayName:role};};
 const wh=(await stock('create_warehouse',{name:'History'}))[1].id;
 const create=async(code,cost)=>{const id=(await stock('create_item',{code,name:code,barcode:code}))[1].id;assert.equal((await stock('record_purchase',{item_id:id,warehouse_id:wh,qty:5,unit_cost:cost}))[0],200);return id;};
 const main=await create('MAIN',100),gift=await create('GIFT',10),other=await create('OTHER',30);
 const qty=id=>sqlite.prepare('SELECT SUM(qty_delta) n FROM inventory_stock_moves WHERE item_id=?').get(id).n;
 const value=id=>sqlite.prepare('SELECT SUM(value_cents) n FROM inventory_stock_moves WHERE item_id=?').get(id).n;
 const sale={item_id:main,warehouse_id:wh,qty:1,unit_price:200,sold_at:'2026-01-05T10:00:00.000Z',has_accessories:true,gifts:[{item_id:gift,qty:1}],units:[{serial:'SERIAL',barcode:'',note:''}]};
 as('operator');const [,pending]=await stock('record_sale',sale);as('manager');const [,approved]=await stock('approve_sale',{},pending.id);const id=approved.id;
 const modify=async(action,revision,data,reason='Correct details',request_id=crypto.randomUUID())=>json(await post(stockRoute,{action,id,request_id,data:{revision,reason,sale:data}}));
 as('operator');assert.equal((await modify('update_sale',1,sale))[0],403);assert.equal((await modify('delete_sale',1))[0],403);
 assert.equal((await json(await stockRoute.GET(new Request('https://crm.test/api/inventory?view=sale_detail&id='+id))))[0],403);
 as('manager');await stock('record_purchase',{item_id:main,warehouse_id:wh,qty:5,unit_cost:300});
 const oldValue=value(main);let [status,result]=await modify('update_sale',1,{...sale,seller:'operator@example.test',customer_name:'Fixed name'});assert.equal(status,200,JSON.stringify(result));assert.equal(result.id,id);
 assert.equal(qty(main),9);assert.equal(value(main),oldValue,'metadata edit preserves historical cost');assert.equal(sqlite.prepare('SELECT cost_cents FROM inventory_sales WHERE id=?').get(id).cost_cents,11000);
 assert.equal(sqlite.prepare("SELECT SUM(qty_delta) n FROM inventory_stock_moves WHERE ref_id=? AND item_id=? AND occurred_at<?").get(id,main,'2026-02-01').n,-1,'past outflow must not double on edit');
 assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM direct_sale_requests WHERE id=?').get(pending.id).payload).customer_name,'Fixed name');
 assert.equal((await modify('update_sale',1,sale))[0],409);
 assert.equal((await modify('delete_sale',2,undefined,''))[0],400);
 assert.equal((await modify('update_sale',2,{...sale,qty:999}))[0],409);assert.equal(qty(main),9);assert.equal(qty(gift),4);assert.equal(sqlite.prepare('SELECT revision FROM inventory_sales WHERE id=?').get(id).revision,2);
 const changed={...sale,item_id:other,qty:2,gifts:[],has_accessories:false,units:[]};const receipt=crypto.randomUUID();
 assert.equal((await modify('update_sale',2,changed,'Changed product',receipt))[0],200);assert.equal((await modify('update_sale',2,changed,'Changed product',receipt))[0],200);
 assert.equal(qty(main),10);assert.equal(qty(gift),5);assert.equal(qty(other),3);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM inventory_units WHERE ref_id=?').get(id).n,0);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM inventory_sale_changes WHERE sale_id=?').get(id).n,2);
 const detail=(await json(await stockRoute.GET(new Request('https://crm.test/api/inventory?view=sale_detail&id='+id))))[1];assert.equal(detail.sale.revision,3);assert.equal(detail.history.length,2);
 as('director');const deletion=crypto.randomUUID();assert.equal((await modify('delete_sale',3,undefined,'Duplicate sale',deletion))[0],200);assert.equal((await modify('delete_sale',3,undefined,'Duplicate sale',deletion))[0],200);
 assert.equal(qty(other),5);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM inventory_sales WHERE id=?').get(id).n,0);assert.ok(sqlite.prepare('SELECT deleted_at FROM direct_sale_requests WHERE id=?').get(pending.id).deleted_at);
 assert.equal(sqlite.prepare('SELECT SUM(qty_delta) n FROM inventory_stock_moves WHERE ref_id=? AND occurred_at<?').get(id,'2026-02-01').n,0,'deletion cancels original dated outflow');
 const list=(await json(await stockRoute.GET(new Request('https://crm.test/api/inventory?view=sale_requests&status=approved'))))[1];assert.equal(list.count,0);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM inventory_sale_changes WHERE sale_id=?').get(id).n,3);
 assert.equal((await modify('delete_sale',3))[0],404);assert.equal(qty(other),5);
 const [,linked]=await stock('record_sale',sale);sqlite.prepare('UPDATE inventory_sales SET lead_id=? WHERE id=?').run('loan',linked.id);
 assert.equal((await json(await post(stockRoute,{action:'delete_sale',id:linked.id,request_id:crypto.randomUUID(),data:{revision:1,reason:'No'}})))[0],409);
 const [,race]=await stock('record_sale',{...sale,gifts:[]});
 access.member=async()=>sqlite.prepare('SELECT * FROM members WHERE email=?').get(user.email);
 const raceResult=await Promise.all([1,2].map(n=>stock('update_sale',{revision:1,reason:'Concurrent '+n,sale:{...sale,gifts:[],unit_price:200+n}},race.id)));
 assert.deepEqual(raceResult.map(r=>r[0]).sort(),[200,409]);assert.equal(sqlite.prepare('SELECT revision FROM inventory_sales WHERE id=?').get(race.id).revision,2);
 console.log('PASS: approved sale edit/delete permissions, historical cost preservation, stock and gifts reversal, serial replacement, insufficient-stock rollback, stale revisions, idempotency, audit, request synchronization and loan-sale protection.');
})().catch(e=>{console.error(e);process.exitCode=1;});
`);
