process.env.CRM_OWNER_EMAIL='owner@example.test';
const {DatabaseSync}=require('node:sqlite');const {generateKeyPairSync,randomBytes}=require('node:crypto');const ts=require('typescript');const fs=require('fs');const assert=require('node:assert/strict');
const sqlite=new DatabaseSync(':memory:');for(const p of fs.readdirSync('drizzle').filter(p=>p.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+p,'utf8'));
class S{constructor(sql,args=[]){this.sql=sql;this.args=args;}bind(...a){return new S(this.sql,a)}async first(){return sqlite.prepare(this.sql).get(...this.args)||null}async all(){return{results:sqlite.prepare(this.sql).all(...this.args)}}async run(){const r=sqlite.prepare(this.sql).run(...this.args);return{meta:{changes:Number(r.changes)}}}}
const DB={prepare:s=>new S(s),batch:async ss=>{sqlite.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
let user={userId:'o',email:'owner@example.test',displayName:'Owner'};const env={DB,CRM_CONNECTION_ENCRYPTION_KEY:randomBytes(32).toString('base64')};const deps={'@/lib/runtime':{env},'../app/session':{getCurrentUser:async()=>user}};
function load(path){const source=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const m={exports:{}};new Function('require','module','exports',source)(n=>deps[n]||require(n),m,m.exports);return m.exports;}
deps['./runtime']=deps['@/lib/runtime'];const access=load('lib/access.ts');deps['@/lib/access']=access;const notifications=load('lib/notifications.ts');deps['@/lib/notifications']=notifications;deps['./notifications']=notifications;const crm=load('lib/crm.ts');deps['./crm']=crm;deps['@/lib/crm']=crm;const model=load('lib/sheet-model.ts');deps['./sheet-model']=model;deps['@/lib/assign']=load('lib/assign.ts');deps['./assign']=deps['@/lib/assign'];const sheets=load('lib/sheets.ts');deps['@/lib/sheets']=sheets;const sound=load('lib/sound.ts');deps['./sound']=sound;deps['@/lib/sound']=sound;const settings=load('lib/settings.ts');deps['@/lib/settings']=settings;const sms=load('lib/sms.ts');deps['@/lib/sms']=sms;const api=load('app/api/crm/route.ts');deps['../crm/route']=api;const integration=load('app/api/sheets/route.ts');
const serial=Date.now()/86400000+25569+8/24;
let columns=[ [['Timestamp'],[serial]], [['Холбогдох утасны дугаар'],['99112233']], [['Таны зээлээр авахыг хүсэж буй бараа'],['Laptop']], [['Холбогдсон ажилтан/Нэр'],['Есүй']], [['ТӨЛӨВ'],['Холбогдоогүй']], [['Регистрийн дугаар'],['АБ99112233']] ];
let googleCalls=0;global.fetch=async(url,opts={})=>{googleCalls++;if(String(url)==='https://oauth2.googleapis.com/token'){const jwt=new URLSearchParams(opts.body).get('assertion');const claim=JSON.parse(Buffer.from(jwt.split('.')[1],'base64url'));assert.equal(claim.scope,'https://www.googleapis.com/auth/spreadsheets.readonly');assert.equal(claim.aud,'https://oauth2.googleapis.com/token');return Response.json({access_token:'test-only'});}if(String(url).includes('values:batchGet')){const parsed=new URL(url);assert.equal(parsed.searchParams.get('dateTimeRenderOption'),'SERIAL_NUMBER');const ranges=parsed.searchParams.getAll('ranges');assert.equal(ranges.length,6);assert.ok(ranges.some(r=>/!C1:/.test(r)));return Response.json({valueRanges:columns.map(values=>({values}))});}return Response.json({sheets:[{properties:{title:model.defaults.tab,gridProperties:{rowCount:42683,columnCount:8}}}]});};
async function post(action,extra={}){const r=await integration.POST(new Request('https://crm.test/api/sheets',{method:'POST',headers:{Origin:'https://crm.test','Content-Type':'application/json'},body:JSON.stringify({action,...extra})}));return[r.status,await r.json()];}
(async()=>{
 await api.GET(new Request('https://crm.test/api/crm'));sqlite.prepare("INSERT INTO members(email,user_id,name,role,active) VALUES(?,?,'Agent','agent',1)").run('agent@example.test','a');sqlite.prepare("INSERT INTO members(email,user_id,name,role,active) VALUES(?,?,'Second','agent',1)").run('second@example.test','b');
 // Date compatibility keeps source identity stable and refuses fabricated calendar days.
 assert.equal(model.timestamp('11/30/2025 16:47:07'+String.fromCharCode(92)),'2025-11-30T08:47:07.000Z');
 assert.equal(model.timestamp('2026-09-15 13:40:00'),'2026-09-15T05:40:00.000Z');
 assert.equal(model.timestamp('9/15/2026 1:40:00 PM'),'2026-09-15T05:40:00.000Z');
 assert.equal(model.timestamp('2026-09-15T05:40:00.123Z'),'2026-09-15T05:40:00.123Z');
 assert.equal(model.timestamp('2/29/2024 00:00:00'),'2024-02-28T16:00:00.000Z');
 for(const badDate of ['2/29/2025 10:00:00','4/31/2026 10:00:00','2026-09-15T24:00:00','2026-09-15T10:60:00','tumen mall','11/','',null])assert.throws(()=>model.timestamp(badDate));
 assert.equal(model.timestamp(serial),new Date(Math.round((serial-25569)*86400000)-8*3600000).toISOString());
 assert.equal(crm.requestDateLabel('2025-12-31T17:00:00.000Z'),'2026-01-01 01:00:00 · УБ');
 assert.equal(crm.requestDateLabel('bad'),'Огноо шалгах');
 const invalidDateColumns=columns.map(c=>c.map(r=>[...r]));invalidDateColumns[0][1]=['text'];const dateIssue=model.transformRows(invalidDateColumns,model.defaults);assert.equal(dateIssue.counts.invalidDates,1);assert.equal(dateIssue.rows.length,0);assert.ok(dateIssue.issues[0].reason.startsWith('A2:'));
 const boundary=columns.map(c=>c.map(r=>[...r]));boundary[0][1]=['1/1/2026 00:15:00'];assert.equal(model.transformRows(boundary,{...model.defaults,includeHistory:false}).rows.length,1);boundary[0][1]=['12/31/2025 23:59:00'];assert.equal(model.transformRows(boundary,{...model.defaults,includeHistory:false}).rows.length,0);
 let parsed=model.transformRows(columns,{...model.defaults,aliases:{'Есүй':'agent@example.test'}});assert.equal(parsed.rows.length,1);assert.equal(parsed.rows[0].ownerEmail,'agent@example.test');assert.equal(parsed.rows[0].status,'unreachable');
 // id өгөхгүй sync нь бүх холболтыг нэг дор шалгаад, эх нь болгонийг connections[]-д тайлагнана.
 {const r=(await post('sync'))[1];assert.equal(r.state,'synced');assert.ok(r.connections.every(c=>c.state==='not_connected'));}
 const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048,privateKeyEncoding:{format:'pem',type:'pkcs8'},publicKeyEncoding:{format:'pem',type:'spki'}});const credential={type:'service_account',client_email:'crm@test-project.iam.gserviceaccount.com',private_key:privateKey};
 let config={...model.defaults,aliases:{'Есүй':'agent@example.test'}};assert.equal((await post('save',{config,credential}))[0],200);const encrypted=sqlite.prepare('SELECT credential FROM sheet_connection').get().credential;assert.ok(!encrypted.includes('PRIVATE KEY'));let publicData=await sheets.publicConnection();assert.ok(!JSON.stringify(publicData).includes(privateKey));assert.equal((await post('toggle',{enabled:true}))[0],400);
 assert.equal((await post('test'))[0],200);assert.equal((await post('toggle',{enabled:true}))[0],200);let [status,r]=await post('sync',{id:1});assert.equal(status,200,JSON.stringify(r));assert.equal(r.added,1);let lead=sqlite.prepare('SELECT * FROM leads').get();assert.equal(lead.owner,'agent@example.test');assert.equal((await notifications.listNotices('agent@example.test')).items.length,1);let count=sqlite.prepare('SELECT COUNT(*) n FROM activities').get().n;
 assert.equal((await post('sync',{id:1}))[1].state,'waiting');sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();r=(await post('sync',{id:1}))[1];assert.equal(r.added,0);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM activities').get().n,count);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM notifications').get().n,2);
 sqlite.prepare("UPDATE leads SET status='materials',next_at='2026-12-01T02:00:00.000Z',next_action='Keep agreement'").run();columns[3][1]=['Ариунболор'];config.aliases['Ариунболор']='second@example.test';await post('save',{config});await post('test');await post('toggle',{enabled:true});sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();r=(await post('sync',{id:1}))[1];assert.equal(r.reassigned,1);lead=sqlite.prepare('SELECT * FROM leads').get();assert.equal(lead.owner,'second@example.test');assert.equal((await notifications.listNotices('agent@example.test')).items.length,0);assert.equal((await notifications.listNotices('second@example.test')).items.length,1);assert.equal(lead.status,'materials');assert.equal(lead.next_action,'Keep agreement');assert.equal(lead.next_at,'2026-12-01T02:00:00.000Z');
 user={userId:'a',email:'agent@example.test',displayName:'Agent'};let response=await api.GET(new Request('https://crm.test/api/crm?id='+lead.id));assert.equal(response.status,404);assert.equal((await integration.GET()).status,403);assert.equal((await post('save',{config}))[0],403);user={userId:'o',email:'owner@example.test',displayName:'Owner'};
 // Reassignment is recorded even when there is no matching employee; previous agent loses visibility.
 columns[3][1]=['Unknown'];sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();await post('sync',{id:1});lead=sqlite.prepare('SELECT * FROM leads').get();assert.equal(lead.owner,'__sheet_unassigned__');assert.equal(lead.next_action,'Keep agreement');
 // Reordering does not duplicate a source identity.
 columns=columns.map(c=>[c[0],[],...c.slice(1)]);sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();await post('sync',{id:1});assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,1);
 // Terminal state and suppression are never reopened by the assignment sync.
 sqlite.prepare("UPDATE leads SET status='won',next_at=NULL,next_action='Closed'").run();sqlite.prepare("INSERT INTO suppressions VALUES('99112233','stop','Owner','2026-09-15')").run();columns[3][2]=['Есүй'];sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();await post('sync',{id:1});lead=sqlite.prepare('SELECT * FROM leads').get();assert.equal(lead.status,'won');assert.equal(lead.next_at,null);
 // Registry backfill runs even with unchanged assignee, but never overwrites a manual edit.
 sqlite.prepare('DELETE FROM suppressions').run();sqlite.prepare("UPDATE leads SET status='materials',registration='' WHERE id=?").run(lead.id);
 sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();r=(await post('sync',{id:1}))[1];assert.equal(r.backfilled,1);assert.equal(sqlite.prepare('SELECT registration FROM leads WHERE id=?').get(lead.id).registration,'АБ99112233');
 sqlite.prepare("UPDATE leads SET registration='ВГ00112233',registration_manual=1 WHERE id=?").run(lead.id);columns[5][2]=['ДД99112233'];sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();await post('sync',{id:1});assert.equal(sqlite.prepare('SELECT registration FROM leads WHERE id=?').get(lead.id).registration,'ВГ00112233');
 // A later request on the same phone is a distinct source event and is not lost.
 columns=columns.map(c=>[...c,[...c[2]]]);columns[0][3]=[serial+1];sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();r=(await post('sync',{id:1}))[1];assert.equal(r.added,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM leads').get().n,2);sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();assert.equal((await post('sync',{id:1}))[1].added,0);
 const bad=columns.map(c=>c.map(r=>[...r]));bad[4][2]=['Unmapped outcome'];assert.equal(model.transformRows(bad,config).rows.length,2);assert.equal(model.transformRows(bad,config).rows[0].status,'review');assert.equal(model.transformRows(bad,config).issues.length,1);
 // Header change is a fail-closed read and never mutates existing CRM records.
 const history=sqlite.prepare('SELECT COUNT(*) n FROM activities').get().n;columns[3][0]=['Moved header'];sqlite.prepare('UPDATE sheet_connection SET last_at=NULL').run();assert.equal((await post('sync',{id:1}))[0],400);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM activities').get().n,history);
 // Deployment setup never overrides an existing key or manually disabled sync.
 env.CRM_GOOGLE_SERVICE_ACCOUNT_JSON=JSON.stringify(credential);
 await post('toggle',{enabled:false});const existing=sqlite.prepare('SELECT * FROM sheet_connection').get();
 assert.equal(await sheets.bootstrapGoogleConnection(),false);assert.equal(sqlite.prepare('SELECT enabled FROM sheet_connection').get().enabled,0);assert.equal(sqlite.prepare('SELECT credential FROM sheet_connection').get().credential,existing.credential);
 // Only admin sync can consume the deployment key; failed header validation stays disabled.
 sqlite.prepare('DELETE FROM sheet_connection').run();user={userId:'a',email:'agent@example.test',displayName:'Agent'};
 // Non-admin хариу нь connections дэлгэрэнгүйг харуулахгүй, зөвхөн ерөнхий төлөвийг л буцаана.
 {const r=(await post('sync'))[1];assert.deepEqual(r,{state:'synced'});}assert.equal(sqlite.prepare('SELECT * FROM sheet_connection').get(),undefined);
 user={userId:'o',email:'owner@example.test',displayName:'Owner'};
 assert.equal((await post('sync'))[0],400);let seeded=sqlite.prepare('SELECT * FROM sheet_connection').get();assert.equal(seeded.enabled,0);assert.equal(seeded.checked,0);assert.ok(seeded.last_error);assert.ok(!seeded.credential.includes('PRIVATE KEY'));
 // A fresh valid setup validates headers before enabling; credentials are never returned.
 sqlite.prepare('DELETE FROM sheet_connection').run();columns[3][0]=['Холбогдсон ажилтан/Нэр'];
 assert.equal(await sheets.bootstrapGoogleConnection(),true);seeded=sqlite.prepare('SELECT * FROM sheet_connection').get();assert.equal(seeded.enabled,1);assert.equal(seeded.checked,1);assert.equal(seeded.email,credential.client_email);assert.ok(!JSON.stringify(await sheets.publicConnection()).includes(privateKey));
 // Legacy saved config gains register mapping and all-history mode without a manual reset.
 const legacy=JSON.parse(JSON.stringify(model.defaults));delete legacy.includeHistory;delete legacy.columns.registration;delete legacy.headers.registration;
 const upgraded=model.configSchema.parse(legacy);assert.equal(upgraded.includeHistory,true);assert.equal(upgraded.columns.registration,'C');
 const historical=columns.map(c=>c.map(r=>[...r]));historical[0][2]=['1/1/2025 00:15:00'];assert.ok(model.transformRows(historical,upgraded).rows.some(r=>r.created.startsWith('2024-12-31')));
 // More than one batch drains with exact pending counts and no duplicate events.
 const many=Array.from({length:101},(_,i)=>({row:i+2,identity:'batch-request-'+i,created:new Date(Date.UTC(2024,0,1,0,i)).toISOString(),phone:'55112233',registration:'АБ99112233',product:'Test laptop',owner:'',ownerEmail:'',status:'new'}));
 sqlite.prepare("UPDATE sheet_connection SET enabled=1,lease='batch-test',lease_until=?").run(Date.now()+120000);
 let batch=await sheets.applyRows(many,[],'batch-test');assert.equal(batch.added,80);assert.equal(batch.pending,21);
 batch=await sheets.applyRows(many,[],'batch-test');assert.equal(batch.added,21);assert.equal(batch.pending,0);
 batch=await sheets.applyRows(many,[],'batch-test');assert.equal(batch.added,0);assert.equal(batch.unchanged,101);
 assert.ok(googleCalls>0);console.log('PASS: encrypted credentials, read-only scopes, registration import, setup gate, idempotency, row reorder, assignment visibility, CRM history/schedule preservation, unknown assignee, terminal/opt-out protection and schema drift.');
})().catch(e=>{console.error(e);process.exit(1)});
