const fs=require('node:fs');const source=fs.readFileSync('tests/serials.test.cjs','utf8');
eval(source.slice(0,source.indexOf('\n(async()=>{'))+String.raw`
const afterTasks=[];let smsCount=0,smsFails=false;
deps['next/server']={after:fn=>afterTasks.push(fn)};
deps['./sms']={SmsError:sms.SmsError,sendSms:async()=>{smsCount++;if(smsFails)throw new sms.SmsError('Test timeout','TIMEOUT');}};
deps['@/lib/web-loan-sms']=load('lib/web-loan-sms.ts');
deps['@/lib/web-loans']=load('lib/web-loans.ts');
const route=load('app/api/integrations/web-loans/route.ts');
const call=(body,token=process.env.CRM_WEB_LOAN_TOKEN)=>route.POST(new Request('https://crm.test/api/integrations/web-loans',{method:'POST',headers:{'Content-Type':'application/json','x-web-loan-token':token||''},body:JSON.stringify(body)}));
(async()=>{
 process.env.CRM_WEB_LOAN_TOKEN='test-only-web-loan-token-at-least-32-characters';
 await crmRoute.GET(new Request('https://crm.test/api/crm'));
 const data={request_id:crypto.randomUUID(),name:'Web customer',phone:'99112233',registration:'АБ12345678',product:'Test phone'};
 assert.equal((await call(data,'bad-token')).status,401);
 assert.equal((await call({...data,owner:'injected@example.test'})).status,400);
 const results=await Promise.all([call(data),call(data)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);
 const first=await results[0].json();const row=sqlite.prepare('SELECT * FROM leads WHERE id=?').get(first.id);
 assert.equal(row.source,'Вэбсайт');assert.equal(row.registration,data.registration);assert.equal(row.owner,'__sheet_unassigned__');
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM web_loan_requests').get().n,1);
 assert.equal((await call({...data,product:'Changed'})).status,409);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM activities WHERE lead_id=?').get(first.id).n,1);
 sqlite.prepare('INSERT INTO app_settings(key,value,updated_at) VALUES(?,?,?)').run('auto_assignment',JSON.stringify({enabled:true,automatic:true,days:7,assignments:[],excluded_emails:[]}),new Date().toISOString());
 for(const role of ['agent','operator']){
  await post(crmRoute,{action:'member',data:{email:role+'@example.test',name:role,role,active:true}});
  sqlite.prepare('INSERT INTO work_shifts(id,day,member_email,person_name,assignment,note,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),deps['./assign'].ubDay(),role+'@example.test',role,'Sales','','test',new Date().toISOString(),new Date().toISOString());
 }
 const dup=await (await call({...data,request_id:crypto.randomUUID()})).json();assert.equal(dup.id,first.id);assert.equal(dup.duplicate,true);
 const assigned=await (await call({...data,request_id:crypto.randomUUID(),product:'Assigned phone'})).json();
 assert.equal(sqlite.prepare('SELECT owner FROM leads WHERE id=?').get(assigned.id).owner,'agent@example.test');
 sqlite.prepare('INSERT INTO suppressions(phone,reason,actor,created_at) VALUES(?,?,?,?)').run('99112234','test','test',new Date().toISOString());
 const suppressed=await (await call({...data,request_id:crypto.randomUUID(),phone:'99112234'})).json();
 assert.equal(sqlite.prepare('SELECT next_at FROM leads WHERE id=?').get(suppressed.id).next_at,null);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM notifications WHERE lead_id=?').get(suppressed.id).n,0);
 await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,0);
 sqlite.prepare("INSERT INTO sms_rules(id,status,message,enabled,created_at,updated_at) VALUES('test-new','new','Request received',1,'now','now') ON CONFLICT(status) DO UPDATE SET enabled=1,message='Request received'").run();
 const smsData={...data,request_id:crypto.randomUUID(),product:'SMS phone'};
 const smsLead=await (await call(smsData)).json();await call(smsData);
 assert.equal(sqlite.prepare("SELECT kind FROM activities WHERE id=?").get('sms-'+smsLead.id).kind,'sms_pending');
 await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,1);
 assert.ok(sqlite.prepare('SELECT note FROM activities WHERE id=?').get('sms-'+smsLead.id).note.includes('Unitel'));
 await call(smsData);await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,1);
 await call({...data,request_id:crypto.randomUUID(),phone:'99112234'});await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,1);
 smsFails=true;const failedData={...data,request_id:crypto.randomUUID(),product:'Failed phone'};await call(failedData);await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,2);
 await call(failedData);await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,2);
 const disabledData={...data,request_id:crypto.randomUUID(),product:'Disabled phone'};await call(disabledData);sqlite.prepare("UPDATE sms_rules SET enabled=0 WHERE status='new'").run();await Promise.all(afterTasks.splice(0).map(fn=>fn()));assert.equal(smsCount,2);
 const parallelData={...data,product:'Parallel Same Day'};const parallel=await Promise.all([call({...parallelData,request_id:crypto.randomUUID()}),call({...parallelData,request_id:crypto.randomUUID()})]);const parallelBodies=await Promise.all(parallel.map(r=>r.json()));assert.equal(parallelBodies[0].id,parallelBodies[1].id);
 const normalized=await (await call({...parallelData,product:'  parallel   same day ',request_id:crypto.randomUUID()})).json();assert.equal(normalized.id,parallelBodies[0].id);
 sqlite.prepare('UPDATE leads SET created_at=? WHERE id=?').run(new Date(Date.now()-86400000).toISOString(),normalized.id);const nextDay=await (await call({...parallelData,request_id:crypto.randomUUID()})).json();assert.notEqual(nextDay.id,normalized.id);
 console.log('PASS: web intake auth, strict validation, concurrent retry dedup, conflicts, source, audit and suppression');
})().catch(e=>{console.error(e);process.exit(1)});
`);
