'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Link2,LayoutDashboard,ListFilter,RefreshCw,ChartNoAxesCombined,Users,BookOpen,Plus,Search,ArrowUpRight,Clock,Phone,Check,Loader2,Upload,Download,LogOut,ShieldCheck,ArrowRight,Inbox,CheckCircle2,ChevronLeft,ChevronRight,ChevronsLeft,ChevronsRight,Ban,MessageSquare,Settings,Layers} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {Toaster} from '@/components/ui/sonner';import {toast} from 'sonner';
import SheetsPanel from './sheets-panel';
import SettingsPanel from './settings-panel';
import NotificationBell from './notification-bell';
import {stages,sources,roles,kinds,dateLabel,requestDateLabel,closed,localInput,fromInput,csvCell,parseCSV,normalizePhone,type Lead,type Member,type Activity} from '@/lib/crm';
type Data={me:Member;leads:Lead[];count:number;page:number;members:Member[];stats:{total:number;won:number;due:number;recycled:number;recycle_overdue:number};distribution:{status:string;count:number}[];byMember:{email:string;name:string;total:number;counts:Record<string,number>;activities:number}[];settings:{notification_sound:string};candidateGroups:{status:string;count:number}[]};
type Detail={lead:Lead;activities:Activity[]};
const nav=[{id:'today',label:'Өнөөдрийн ажил',icon:LayoutDashboard},{id:'all',label:'Бүх хүсэлт',icon:ListFilter},{id:'candidates',label:'Дахин ажиллах бүлэг',icon:Layers},{id:'recycle',label:'Recycle хөтөлбөр',icon:RefreshCw},{id:'reports',label:'Тайлан',icon:ChartNoAxesCombined},{id:'team',label:'Манай баг',icon:Users},{id:'sheets',label:'Google Sheets',icon:Link2},{id:'settings',label:'Тохиргоо',icon:Settings},{id:'guide',label:'Ажлын заавар',icon:BookOpen}];
// Recycle гарын авлагын 4 бүлэг ↔ одоо байгаа lead статус (нэр өөр, утга адилхан).
const candidateGroupOrder:[string,string][]=[['appointment','Өдөр товлосон'],['materials','Материал хүлээгдэж буй'],['pending','Хүлээгдэж байгаа'],['unreachable','Холбогдоогүй']];
const adminOnlyNav=new Set(['sheets','settings']);
async function api(body:unknown){const r=await fetch('/api/crm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string;id?:string;added?:number;skipped?:number;ok?:boolean};if(!r.ok)throw new Error(d.error||'Хүсэлт амжилтгүй.');return d;}
function download(name:string,text:string){const u=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function Chip({lead}:{lead:Lead}){return <span className={'stage stage-'+(lead.blocked?'blocked':lead.status)}>{lead.blocked?'Дахин холбогдохгүй':stages[lead.status]}</span>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
// 5 хуудасны дугаарыг нэг багцаар харуулна; багц дуусахад дараагийн 5-руу шилжинэ.
function PageNumbers({page,totalPages,loading,onChange}:{page:number;totalPages:number;loading:boolean;onChange:(p:number)=>void}){
 const groupStart=Math.floor((page-1)/5)*5+1,groupEnd=Math.min(groupStart+4,totalPages),pages=Array.from({length:groupEnd-groupStart+1},(_,i)=>groupStart+i);
 return <Pagination className="page-controls"><PaginationContent>
 <PaginationItem><Button size="sm" variant="outline" disabled={groupStart<=1||loading} onClick={()=>onChange(groupStart-5)} aria-label="Өмнөх 5 хуудас"><ChevronsLeft size={16}/></Button></PaginationItem>
 <PaginationItem><Button size="sm" variant="outline" disabled={page<=1||loading} onClick={()=>onChange(page-1)} aria-label="Өмнөх хуудас"><ChevronLeft size={16}/></Button></PaginationItem>
 {pages.map(p=><PaginationItem key={p}><Button size="sm" variant={p===page?'default':'outline'} className={p===page?'primary':''} disabled={loading} onClick={()=>onChange(p)} aria-label={p+'-р хуудас'} aria-current={p===page?'page':undefined}>{p}</Button></PaginationItem>)}
 <PaginationItem><Button size="sm" variant="outline" disabled={page>=totalPages||loading} onClick={()=>onChange(page+1)} aria-label="Дараагийн хуудас"><ChevronRight size={16}/></Button></PaginationItem>
 <PaginationItem><Button size="sm" variant="outline" disabled={groupEnd>=totalPages||loading} onClick={()=>onChange(groupEnd+1)} aria-label="Дараагийн 5 хуудас"><ChevronsRight size={16}/></Button></PaginationItem>
 </PaginationContent></Pagination>;
}
// Гарын авлагын багтаамжийн томьёо: нийт минут ÷ нэг хүсэлтэд зарцуулах дундаж минут.
// Хэмжсэн бүтээмж биш, зөвхөн төлөвлөлтийн санал тул хадгалахгүй, зөвхөн клиент дээр тооцно.
function CapacityCalculator({total}:{total:number}){
 const [agents,setAgents]=useState(2),[minutesPerAgent,setMinutesPerAgent]=useState(180),[minutesPerLead,setMinutesPerLead]=useState(6);
 const dailyCapacity=minutesPerLead>0?Math.floor((agents*minutesPerAgent)/minutesPerLead):0;
 const daysNeeded=dailyCapacity>0?Math.ceil(total/dailyCapacity):0;
 return <div className="panel capacity-calc"><div className="eyebrow">БАГТААМЖИЙН ТӨЛӨВЛӨГӨӨ</div><h2>Өдрийн боломжит хүсэлт</h2><p className="muted">Нийт минут ÷ нэг хүсэлтэд зарцуулах дундаж минут. Энэ нь хэмжсэн бүтээмж биш, төлөвлөлтийн санал; туршилтын эхний өдрүүдээр бодит хугацаагаар шинэчилнэ.</p>
 <div className="capacity-inputs"><Field label="Ажилтны тоо"><Input type="number" min={1} max={999} value={agents} onChange={e=>setAgents(Math.max(1,Math.min(999,Number(e.target.value)||1)))}/></Field><Field label="Ажилтан тус бүр гаргах минут/өдөр"><Input type="number" min={1} max={1440} value={minutesPerAgent} onChange={e=>setMinutesPerAgent(Math.max(1,Math.min(1440,Number(e.target.value)||1)))}/></Field><Field label="Нэг хүсэлтэд зарцуулах дундаж минут"><Input type="number" min={1} max={999} value={minutesPerLead} onChange={e=>setMinutesPerLead(Math.max(1,Math.min(999,Number(e.target.value)||1)))}/></Field></div>
 <div className="capacity-result"><div><strong>{(agents*minutesPerAgent).toLocaleString()}</strong><span>Нийт минут ({agents} × {minutesPerAgent})</span></div><div><strong>{dailyCapacity.toLocaleString()}</strong><span>Өдрийн багтаамж</span></div><div><strong>{total.toLocaleString()}</strong><span>Одоогийн нэр дэвшигч</span></div><div><strong>{daysNeeded?daysNeeded.toLocaleString():'—'}</strong><span>Ажлын өдөр шаардагдана</span></div></div></div>;
}
export default function CRM(){
 const [view,setView]=useState('today'),[q,setQ]=useState(''),[status,setStatus]=useState(''),[owner,setOwner]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[reportFrom,setReportFrom]=useState(''),[reportTo,setReportTo]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[create,setCreate]=useState(false),[importOpen,setImportOpen]=useState(false),[detail,setDetail]=useState<Detail|null>(null),[detailId,setDetailId]=useState(''),[detailError,setDetailError]=useState(''),[busy,setBusy]=useState(false),[teamEdit,setTeamEdit]=useState<Member|null>(null),[teamOpen,setTeamOpen]=useState(false);
 const seq=useRef(0);const detailSeq=useRef(0);
 const reload=useCallback(()=>setRefresh(x=>x+1),[]);
 const clearFilters=useCallback(()=>{setQ('');setStatus('');setOwner('');setDateFrom('');setDateTo('');},[]);
 const navigate=useCallback((v:string)=>{setView(v);setPage(1);clearFilters();},[clearFilters]);
 const filtered=!!(q||status||owner||dateFrom||dateTo);
 useEffect(()=>{const controller=new AbortController();const n=++seq.current;setLoading(true);const timer=setTimeout(async()=>{try{const r=await fetch('/api/crm?'+new URLSearchParams({view,q,status,owner,from:dateFrom,to:dateTo,rfrom:reportFrom,rto:reportTo,page:String(page)}),{signal:controller.signal});const d=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(d.error);if(n===seq.current){setData(d);setError('');}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Алдаа гарлаа.');}finally{if(n===seq.current)setLoading(false);}},q?250:0);return()=>{clearTimeout(timer);controller.abort();};},[view,q,status,owner,dateFrom,dateTo,reportFrom,reportTo,page,refresh]);
 const openLead=useCallback(async(id:string)=>{const n=++detailSeq.current;setDetailId(id);setDetail(null);setDetailError('');try{const r=await fetch('/api/crm?id='+encodeURIComponent(id));const d=await r.json() as Detail&{error?:string};if(!r.ok)throw new Error(d.error);if(n===detailSeq.current)setDetail(d);}catch(e){if(n===detailSeq.current)setDetailError((e as Error).message);}},[]);
 const mutate=async(body:unknown)=>{setBusy(true);try{const r=await api(body);toast.success('Амжилттай хадгаллаа');reload();if(detailId)await openLead(detailId);return r;}catch(e){toast.error((e as Error).message);return null;}finally{setBusy(false);}};
 useEffect(()=>{
 const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();
 const register=(t:unknown)=>{try{void Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}};
 register({name:'navigate_crm',description:'AntMall CRM-ийн сонгосон хэсгийг нээнэ. Мэдээлэл өөрчлөхгүй.',inputSchema:{type:'object',properties:{view:{type:'string',enum:nav.map(n=>n.id)}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const v=(input as {view?:string})?.view;if(!nav.some(n=>n.id===v))throw new Error('Unknown view');navigate(v!);await new Promise(r=>setTimeout(r,0));return{view:v};}});
 register({name:'start_request_creation',description:'Шинэ хүсэлтийн маягт нээнэ. Бүртгэл хадгалахгүй.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments expected');setCreate(true);await new Promise(r=>setTimeout(r,0));return{form:'open',saved:false};}});
 return()=>life.abort();},[navigate]);
 useEffect(()=>{if(!data?.me)return;let stopped=false,running=false;const tick=async()=>{if(running||document.visibilityState!=='visible')return;running=true;try{const r=await fetch('/api/sheets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync'})});if(r.ok&&!stopped)reload();if(detailId){const check=await fetch('/api/crm?id='+encodeURIComponent(detailId));if(check.status===404&&!stopped){setDetailId('');setDetail(null);toast.info('Хүсэлтийн хариуцагч өөрчлөгдсөн байна.');}}}catch{}finally{running=false;}};void tick();const timer=setInterval(tick,30000);const visible=()=>{if(document.visibilityState==='visible')void tick();};document.addEventListener('visibilitychange',visible);return()=>{stopped=true;clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[data?.me.email,reload,detailId]);
 const title=nav.find(n=>n.id===view)!.label;
 const reportTotal=data?.distribution.reduce((n,d)=>n+d.count,0)||0,reportWon=data?.distribution.find(d=>d.status==='won')?.count||0;
 return <SidebarProvider><Sidebar className="crm-sidebar"><SidebarHeader className="brand"><div className="brandmark">A<span/></div><div><strong>AntMall<span className="brand-dot">.</span></strong><small>TEAM WORKSPACE</small></div></SidebarHeader><SidebarContent><div className="nav-caption">АЖЛЫН ОРЧИН</div><SidebarMenu>{nav.filter(n=>!adminOnlyNav.has(n.id)||data?.me.role==='admin').map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>navigate(n.id)} className="nav-button"><n.icon size={19}/><span>{n.label}</span>{n.id==='today'&&!!data?.stats.due&&<b className="nav-count">{data.stats.due}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-tip"><ShieldCheck size={22}/><strong>Нэг хүсэлт. Нэг хариуцагч.</strong><p>Товоо төлөвлөж, харилцагчтай хийсэн алхам бүрээ бүртгээрэй.</p></div></SidebarContent><SidebarFooter className="sidebar-user"><div className="avatar">{data?.me.name?.slice(0,1)||'A'}</div><div className="user-label"><strong>{data?.me.name||'AntMall баг'}</strong><small>{data?roles[data.me.role]:'Түр хүлээнэ үү'}</small></div><a href="/logout" target="_top" title="Гарах"><LogOut size={17}/></a></SidebarFooter></Sidebar>
 <SidebarInset className="workspace"><header className="topbar"><div className="row"><SidebarTrigger/><span>AntMall <span className="muted">/ Дотоод CRM</span></span></div><div className="row">{data&&<NotificationBell key={data.me.email} email={data.me.email} refresh={refresh} soundPreset={data.settings.notification_sound} onOpenLead={openLead}/>}<span className="private-badge"><span/>Хамгаалалттай орчин</span></div></header><main className="main-content"><div className="page-head"><div><div className="eyebrow">{new Intl.DateTimeFormat('mn-MN',{timeZone:'Asia/Ulaanbaatar',year:'numeric',month:'long',day:'numeric'}).format(new Date())} · УЛААНБААТАР</div><h1>{title}<span className="title-dot">.</span></h1><p>{view==='today'?'Тов нь болсон хүсэлтүүдээ нэг дороос удирдаарай.':view==='candidates'?'Recycle хөтөлбөрт сонгох 4 бүлэг: уулзалт, материал, шийдвэр хүлээж буй, холбогдоогүй.':view==='recycle'?'Шийдэгдээгүй хүсэлтэд дараагийн боломжийг нээе.':view==='all'?'Хүсэлтээс борлуулалт хүртэлх бүх харилцаа.':view==='reports'?'Одоогийн бүртгэлд үндэслэсэн ажлын үр дүн.':view==='team'?'Хариуцлага тодорхой, хамтын ажиллагаа ойлгомжтой.':view==='settings'?'Системийн ерөнхий тохиргоо.':'Өдөр тутмын ажилдаа дагах нэгдсэн дараалал.'}</p></div><div className="head-actions"><Button variant="outline" onClick={reload} disabled={loading} title="Шинэчлэх"><RefreshCw size={16} className={loading?'spin':''}/></Button><Button className="primary" onClick={()=>setCreate(true)} disabled={!data}><Plus size={17}/>Шинэ хүсэлт</Button></div></div>
 {error&&<div role="alert" className="error-box">{error} <button onClick={reload}>Дахин оролдох</button></div>}
 {!data&&!error?<div className="loading"><Loader2 className="spin"/>Ажлын орчныг ачаалж байна…</div>:data&&<>
 {['today','all','candidates','recycle','reports'].includes(view)&&<div className="metrics">{[{name:'Нийт хүсэлт',value:data.stats.total,icon:Inbox,key:'all'},{name:'Тов нь болсон',value:data.stats.due,icon:Clock,key:'today'},{name:'Идэвхтэй Recycle',value:data.stats.recycled,icon:RefreshCw,key:'recycle'},{name:'Худалдан авсан',value:data.stats.won,icon:CheckCircle2,key:'reports'}].map((m,i)=><button className={'metric '+(i===1?'metric-focus':'')+(i===2&&data.stats.recycle_overdue?' metric-alert':'')} key={m.key} onClick={()=>navigate(m.key)}><div><span>{m.name}</span><m.icon size={19}/></div><strong>{m.value.toLocaleString()}</strong><small>{i===1?'Одоо холбоо барих ажлууд':i===3?'Худалдан авсан төлөвтэй':i===2?(data.stats.recycle_overdue?data.stats.recycle_overdue.toLocaleString()+' хугацаа хэтэрсэн — ахлагчид мэдэгдэх':'Хаагдаагүй мөчлөгүүд, хугацаандаа'):'Таны харах эрхтэй бүртгэл'}<ArrowUpRight size={13}/></small></button>)}</div>}
 {['today','all','candidates','recycle'].includes(view)&&<><div className={'notice '+(view==='recycle'||view==='candidates'?'purple-notice':'')}><span className="notice-icon">{view==='recycle'?<RefreshCw size={20}/>:view==='candidates'?<Layers size={20}/>:<Clock size={20}/>}</span><div><strong>{view==='candidates'?'Recycle-д орох нэр дэвшигчид, мөчлөгт хараахан ороогүй.':view==='recycle'?'Давтан холбоо барилт, тодорхой хязгаартай.':'Анхны хариуг 5 минутад өгөх зорилттой.'}</strong><p>{view==='candidates'?'Доорх бүлгээс сонгож нээгээд, тохирох бол хүсэлтийн дэлгэрэнгүйгээс "Recycle эхлүүлэх" дарна. Хугацаа хэтэрсэн тов, сүүлийн сонирхлыг нэн түрүүнд авч үзнэ үү.':view==='recycle'?'14 хоногт 3 хариу аваагүй дуудлага. Худалдан авалт, татгалзалт эсвэл холбоо барихгүй хүсэлт ирвэл зогсооно.':'Ажлын цагаар шинэ хүсэлтээ түрүүлж хянаарай. Энд Улаанбаатарын цагаар тов нь болсон ажлууд харагдана.'}</p></div><button onClick={()=>navigate('guide')}>Заавар <ArrowRight size={15}/></button></div>
 {view==='candidates'&&<div className="candidate-groups">{candidateGroupOrder.map(([k,label])=>{const c=data.candidateGroups.find(g=>g.status===k)?.count||0;return <button key={k} className={'candidate-group'+(status===k?' active':'')} onClick={()=>{setStatus(status===k?'':k);setPage(1);}}><strong>{c.toLocaleString()}</strong><span>{label}</span></button>;})}</div>}
 {view==='candidates'&&data.me.role!=='agent'&&<CapacityCalculator total={data.candidateGroups.reduce((n,g)=>n+g.count,0)}/>}
 <section className="table-panel"><div className="table-toolbar"><h2>{view==='today'?'Холбоо барих дараалал':view==='candidates'?'Дахин ажиллах нэр дэвшигчид':view==='recycle'?'Дахин ажиллаж буй хүсэлтүүд':'Хүсэлтийн бүртгэл'}<span>{data.count}</span></h2><div className="row"><Button variant="ghost" size="sm" onClick={()=>{download('AntMall-requests-page-'+page+'.csv',[['Нэр','Утас','Бүтээгдэхүүн','Суваг','Хариуцагч','Төлөв','Хүсэлт ирсэн огноо (УБ)','Дараагийн тов','Дараагийн үйлдэл'],...data.leads.map(l=>[l.name,l.phone,l.product,l.source,l.owner,stages[l.status],requestDateLabel(l.created_at),dateLabel(l.next_at),l.next_action])].map(row=>row.map(csvCell).join(',')).join('\r\n'));toast.success('Харагдаж буй хуудасны бүртгэл татагдлаа.');}}><Download size={15}/>Экспорт</Button><Button variant="outline" size="sm" onClick={()=>setImportOpen(true)}><Upload size={15}/>CSV импорт</Button></div></div><div className="filters"><div className="search"><Search size={17}/><Input aria-label="Хүсэлт хайх" placeholder="Нэр, утас, бүтээгдэхүүнээр хайх…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><select aria-label="Төлөвөөр шүүх" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Бүх төлөв</option>{Object.entries(stages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{data.me.role!=='agent'&&<select aria-label="Хариуцагчаар шүүх" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1);}}><option value="">Бүх хариуцагч</option><option value="__sheet_unassigned__">Хуваарилалт хүлээж буй</option>{data.members.map(m=><option key={m.email} value={m.email}>{m.name}</option>)}</select>}<Input aria-label="Ирсэн огноо: эхлэх" type="date" value={dateFrom} max={dateTo||undefined} onChange={e=>{setDateFrom(e.target.value);setPage(1);}}/><span className="muted">—</span><Input aria-label="Ирсэн огноо: дуусах" type="date" value={dateTo} min={dateFrom||undefined} onChange={e=>{setDateTo(e.target.value);setPage(1);}}/>{filtered&&<Button variant="ghost" size="sm" onClick={()=>{clearFilters();setPage(1);}}>Шүүлтүүр цэвэрлэх</Button>}{loading&&<Loader2 size={17} className="spin muted"/>}</div>
 {data.leads.length?<div className="table-scroll"><Table><TableHeader><TableRow><TableHead>ХАРИЛЦАГЧ</TableHead><TableHead>ХҮСЭЛТ ИРСЭН ОГНОО</TableHead><TableHead>БҮТЭЭГДЭХҮҮН / СУВАГ</TableHead><TableHead>ТӨЛӨВ</TableHead><TableHead>ДАРААГИЙН АЛХАМ</TableHead><TableHead>ХАРИУЦАГЧ</TableHead><TableHead><span className="sr-only">Нээх</span></TableHead></TableRow></TableHeader><TableBody>{data.leads.map(l=><TableRow key={l.id} className="lead-row"><TableCell><button className="lead-link" onClick={()=>openLead(l.id)}><span className="lead-avatar">{l.name.slice(0,1)}</span><span><strong>{l.name}</strong><small>{l.phone}</small></span></button></TableCell><TableCell>{requestDateLabel(l.created_at)}</TableCell><TableCell><strong>{l.product}</strong><small>{l.source}</small></TableCell><TableCell><Chip lead={l}/></TableCell><TableCell><div className={l.next_at&&l.next_at<new Date().toISOString()&&!l.blocked&&!closed.includes(l.status)?'due-text':''}>{l.blocked?'Холбоо барихгүй':dateLabel(l.next_at)}</div><small>{l.blocked?'Харилцагчийн хүсэлтээр':l.next_action}</small></TableCell><TableCell><span className="owner-label">{(l.owner==='__sheet_unassigned__'?'Хуваарилалт хүлээж буй':data.members.find(m=>m.email===l.owner)?.name||l.owner)}</span></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={l.name+' хүсэлт нээх'} onClick={()=>openLead(l.id)}><ArrowUpRight size={18}/></Button></TableCell></TableRow>)}</TableBody></Table></div>:<Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon">{view==='today'?<CheckCircle2/>:<Inbox/>}</EmptyMedia><EmptyTitle>{filtered?'Тохирох хүсэлт олдсонгүй':view==='today'?'Тов нь болсон ажил алга':view==='candidates'?'Нэр дэвшигч алга':view==='recycle'?'Recycle хүсэлт хараахан алга':'Эхний хүсэлтээ бүртгэе'}</EmptyTitle><EmptyDescription>{filtered?'Хайлтын үг болон шүүлтээ өөрчилж үзээрэй.':view==='today'?'Шинэ хүсэлт бүртгэх эсвэл бүх хүсэлтээс дараагийн ажлаа төлөвлөөрэй.':view==='candidates'?'4 бүлгийн аль нэгэнд тохирох, мөчлөгт хараахан ороогүй хүсэлт одоогоор алга.':view==='recycle'?'Хүсэлтийн дэлгэрэнгүйг нээгээд Recycle эхлүүлэх үйлдлийг сонгоно.':'Хүсэлтээ гараар нэмэх эсвэл CSV файлаас оруулаарай.'}</EmptyDescription></EmptyHeader><Button variant="outline" onClick={()=>view==='all'?setCreate(true):navigate('all')}>{view==='all'?'Шинэ хүсэлт':'Бүх хүсэлт рүү'}<ArrowRight size={16}/></Button></Empty>}
 <div className="table-footer"><span>{data.count?`${(page-1)*50+1}–${Math.min(page*50,data.count)} / ${data.count} хүсэлт`:'0 хүсэлт'} · Экспортод энэ хуудас орно</span><PageNumbers page={page} totalPages={Math.max(1,Math.ceil(data.count/50))} loading={loading} onChange={setPage}/></div></section></>}
 {view==='reports'&&<div className="reports-grid"><div className="report-range panel"><Field label="Хугацааны эхлэл (ирсэн огноо)"><Input type="date" value={reportFrom} max={reportTo||undefined} onChange={e=>setReportFrom(e.target.value)}/></Field><Field label="Хугацааны төгсгөл"><Input type="date" value={reportTo} min={reportFrom||undefined} onChange={e=>setReportTo(e.target.value)}/></Field>{(reportFrom||reportTo)&&<Button variant="ghost" size="sm" onClick={()=>{setReportFrom('');setReportTo('');}}>Бүх хугацаа</Button>}<p className="muted text-sm">{reportFrom||reportTo?`${reportFrom||'…'} — ${reportTo||'өнөөдөр'} хооронд ирсэн ${reportTotal.toLocaleString()} хүсэлтэд үндэслэв.`:'Бүх хугацааны мэдээлэл харагдаж байна. Тодорхой үе харахын тулд огноо сонгоно уу.'}</p></div>
 <section className="panel"><div className="eyebrow">БОРЛУУЛАЛТЫН УРСГАЛ</div><h2>Хүсэлтүүдийн төлөв</h2><p className="muted">Төлөв бүрийн хүсэлтийн тоо, сонгосон хугацаанд эзлэх хувь.</p><div className="bars">{Object.entries(stages).map(([k,v])=>{const c=data.distribution.find(d=>d.status===k)?.count||0;return <div className="bar-row" key={k}><div><span>{v}</span><strong>{c} <small>({reportTotal?Math.round(c/reportTotal*100):0}%)</small></strong></div><div className="bar-track"><span style={{width:(reportTotal?c/reportTotal*100:0)+'%'}}/></div></div>;})}</div></section>
 <section className="panel report-summary"><div className="eyebrow">ХУДАЛДАН АВАЛТ</div><strong className="big-number">{reportTotal?(reportWon/reportTotal*100).toFixed(1):'0.0'}<span>%</span></strong><h2>Бүртгэлийн хөрвөлт</h2><p>Худалдан авсан төлөвтэй хүсэлт ÷ сонгосон хугацаанд ирсэн харах эрхтэй хүсэлт.</p><hr/><p>Recycle хөтөлбөрийн нэмэлт үр нөлөө эсвэл орлогын тооцоо биш.</p><Button variant="outline" onClick={()=>navigate('all')}>Бүртгэлээ харах<ArrowRight size={16}/></Button></section>
 {data.me.role!=='agent'&&<section className="panel team-report"><div className="eyebrow">БАГИЙН ГИШҮҮД</div><h2>Ажилтан тус бүрийн үзүүлэлт</h2><p className="muted">Сонгосон хугацаанд хуваарилагдсан хүсэлт төлөв тус бүрээр, хийсэн үйлдлийн тоо (дуудлага/тэмдэглэл), хөрвөлт.</p><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>АЖИЛТАН</TableHead><TableHead>НИЙТ</TableHead>{Object.entries(stages).map(([k,v])=><TableHead key={k}>{v}</TableHead>)}<TableHead>ҮЙЛДЭЛ</TableHead><TableHead>ХӨРВӨЛТ</TableHead></TableRow></TableHeader><TableBody>{[...data.byMember].sort((a,b)=>b.total-a.total).map(r=><TableRow key={r.email}><TableCell><strong>{r.name}</strong><small>{r.email}</small></TableCell><TableCell>{r.total}</TableCell>{Object.keys(stages).map(k=><TableCell key={k}>{r.counts[k]||0}</TableCell>)}<TableCell>{r.activities}</TableCell><TableCell>{r.total?((r.counts.won||0)/r.total*100).toFixed(1):'0.0'}%</TableCell></TableRow>)}{!data.byMember.length&&<TableRow><TableCell colSpan={14} className="muted">Идэвхтэй ажилтан алга.</TableCell></TableRow>}</TableBody></Table></div></section>}
 </div>}
 {view==='team'&&<section className="panel"><div className="section-heading"><div><h2>Багийн гишүүд</h2><p className="muted">{data.me.role==='agent'?'Танд хуваарилагдсан хүсэлтүүд харагдана.':'И-мэйл хаягаар систем доторх эрхийг удирдана.'}</p></div>{data.me.role==='admin'&&<Button className="primary" onClick={()=>{setTeamEdit(null);setTeamOpen(true);}}><Plus size={16}/>Гишүүн нэмэх</Button>}</div><div className="notice compact"><ShieldCheck size={22}/><p>Систем одоогоор эзэмшигчид нээлттэй. Багийн гишүүнд сайт хуваалцах эрх болон доорх бүртгэл хоёул хэрэгтэй. Энэ маягт и-мэйл илгээхгүй.</p></div><Table><TableHeader><TableRow><TableHead>ГИШҮҮН</TableHead><TableHead>ЭРХ</TableHead><TableHead>ТӨЛӨВ</TableHead><TableHead/></TableRow></TableHeader><TableBody>{data.members.map(m=><TableRow key={m.email}><TableCell><strong>{m.name}</strong><small>{m.email}</small></TableCell><TableCell>{roles[m.role]}</TableCell><TableCell><span className={'stage '+(m.active?'stage-won':'stage-lost')}>{m.active?'Идэвхтэй':'Идэвхгүй'}</span></TableCell><TableCell>{data.me.role==='admin'&&<Button size="sm" variant="outline" onClick={()=>{setTeamEdit(m);setTeamOpen(true);}}>Засах</Button>}</TableCell></TableRow>)}</TableBody></Table></section>}
 {view==='sheets'&&data.me.role==='admin'&&<SheetsPanel members={data.members}/>}
 {view==='settings'&&data.me.role==='admin'&&<SettingsPanel initial={data.settings} onSaved={s=>setData(d=>d?{...d,settings:{...d.settings,...s}}:d)}/>}
 {view==='guide'&&<Guide/>}
 </>}
 <footer className="app-footer"><span>AntMall CRM <span>·</span> Хүсэлтээс харилцаа руу.</span><span>Цагийн бүс: Улаанбаатар (UTC+8)</span></footer></main></SidebarInset>
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Шинэ хүсэлт бүртгэх</DialogTitle><DialogDescription>Хариуцагч болон дараагийн алхмаа хамт төлөвлөөрэй.</DialogDescription></DialogHeader>{data&&<LeadForm members={data.members} me={data.me} busy={busy} onSubmit={async d=>{const r=await mutate({action:'create',data:d});if(r){setCreate(false);navigate('all');if(r.id)openLead(r.id);}}}/>}</DialogContent></Dialog>
 <Sheet open={!!detailId} onOpenChange={o=>{if(!o){detailSeq.current++;setDetailId('');setDetail(null);}}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{detail?.lead.name||'Хүсэлтийн дэлгэрэнгүй'}</SheetTitle><SheetDescription>{detail?`${detail.lead.phone} · ${detail.lead.product}`:'Мэдээлэл болон харилцааны түүх'}</SheetDescription></SheetHeader>{detailError?<div className="error-box">{detailError}<Button onClick={()=>openLead(detailId)}>Дахин нээх</Button></div>:!detail?<div className="loading"><Loader2 className="spin"/>Ачаалж байна…</div>:<div className="detail-body"><div className="row between"><Chip lead={detail.lead}/><span className="muted">{detail.lead.attempts||0}/3 хариу аваагүй · 14 хоног</span></div>{detail.lead.blocked?<div className="error-box"><Ban size={18}/>Энэ дугаарт дахин холбоо барихгүй.</div>:detail.lead.recycle_at&&<div className="notice compact"><RefreshCw size={18}/><p>Recycle эхэлсэн: {dateLabel(detail.lead.recycle_at)}</p></div>}<div className="next-box"><div><strong>Хүсэлт ирсэн огноо</strong><p>{requestDateLabel(detail.lead.created_at)}</p><strong>Регистрийн дугаар</strong><p>{detail.lead.registration||'Бүртгээгүй'}</p></div></div><Tabs defaultValue="activity" key={detail.lead.id}><TabsList className="detail-tabs"><TabsTrigger value="activity">Холбоо барилт</TabsTrigger><TabsTrigger value="edit">Мэдээлэл</TabsTrigger><TabsTrigger value="history">Түүх ({detail.activities.length})</TabsTrigger></TabsList><TabsContent value="activity"><ActivityForm lead={detail.lead} busy={busy} onSubmit={d=>mutate({action:'activity',id:detail.lead.id,version:detail.lead.version,data:d})}/><div className="detail-tools"><Button variant="outline" disabled={busy||!!detail.lead.blocked||!!detail.lead.recycle_at||closed.includes(detail.lead.status)||(detail.lead.attempts||0)>=3} onClick={()=>mutate({action:'recycle',id:detail.lead.id,version:detail.lead.version})}><RefreshCw size={16}/>Recycle эхлүүлэх</Button><Optout disabled={busy||!!detail.lead.blocked} onConfirm={note=>mutate({action:'optout',id:detail.lead.id,version:detail.lead.version,data:{note}})}/></div></TabsContent><TabsContent value="edit">{data&&<LeadForm key={detail.lead.version} lead={detail.lead} members={data.members} me={data.me} busy={busy} onSubmit={d=>mutate({action:'update',id:detail.lead.id,version:detail.lead.version,data:d})}/>}</TabsContent><TabsContent value="history"><div className="timeline">{detail.activities.map(a=><article key={a.id}><span className="timeline-dot"/><div className="row between"><strong>{kinds[a.kind]||a.kind}</strong><time>{dateLabel(a.created_at)}</time></div><p>{a.note}</p><small>{data?.members.find(m=>m.email===a.actor)?.name||a.actor}</small></article>)}</div><p className="muted text-sm">Сүүлийн 100 үйлдэл. Түүхийг устгахгүй.</p></TabsContent></Tabs></div>}</SheetContent></Sheet>
 {data&&<ImportDialog open={importOpen} onOpenChange={setImportOpen} me={data.me} busy={busy} submit={async rows=>{const r=await mutate({action:'import',data:rows});if(r){toast.success(`${r.added} хүсэлт нэмэгдэв. ${r.skipped} давхардсан / хориглосон мөрийг алгасав.`);setImportOpen(false);navigate('all');}}}/>}
 <Dialog open={teamOpen} onOpenChange={setTeamOpen}><DialogContent><DialogHeader><DialogTitle>{teamEdit?'Гишүүний эрх засах':'Багийн гишүүн нэмэх'}</DialogTitle><DialogDescription>Google аккаунтын и-мэйлээр ажилтны эрх олгоно.</DialogDescription></DialogHeader><form key={teamEdit?.email||'new'} className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await mutate({action:'member',data:{email:f.get('email'),name:f.get('name'),role:f.get('role'),active:f.get('active')==='on'}});if(r)setTeamOpen(false);}}><Field label="Нэр"><Input name="name" required maxLength={100} defaultValue={teamEdit?.name}/></Field><Field label="Google-д нэвтрэх и-мэйл"><Input name="email" type="email" required readOnly={!!teamEdit} defaultValue={teamEdit?.email}/></Field><Field label="Эрх"><select name="role" defaultValue={teamEdit?.role||'agent'}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><label className="row"><input type="checkbox" name="active" defaultChecked={teamEdit?!!teamEdit.active:true}/> Идэвхтэй</label><Button className="primary" disabled={busy}>{busy?<Loader2 className="spin"/>:<Check size={16}/>}Хадгалах</Button></form></DialogContent></Dialog>
 <Toaster position="bottom-right" richColors/>
 </SidebarProvider>;
}
function LeadForm({lead,members,me,busy,onSubmit}:{lead?:Lead;members:Member[];me:Member;busy:boolean;onSubmit:(d:unknown)=>unknown}){return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({name:f.get('name'),phone:f.get('phone'),registration:f.get('registration'),product:f.get('product'),source:f.get('source'),owner:f.get('owner'),status:f.get('status'),next_at:fromInput(String(f.get('next_at')||'')),next_action:f.get('next_action')});}}><div className="form-grid"><Field label="Харилцагчийн нэр *"><Input name="name" required maxLength={100} defaultValue={lead?.name} placeholder="Нэр эсвэл байгууллага"/></Field><Field label="Утасны дугаар *"><Input name="phone" required readOnly={!!lead} inputMode="tel" maxLength={16} defaultValue={lead?.phone} placeholder="8 оронтой дугаар"/></Field></div><Field label="Регистрийн дугаар"><Input name="registration" maxLength={10} defaultValue={lead?.registration||''} placeholder="2 кирилл үсэг + 8 цифр" autoComplete="off"/></Field><Field label="Сонирхсон бүтээгдэхүүн *"><Input name="product" required maxLength={160} defaultValue={lead?.product} placeholder="Жишээ: Dell Pro 14"/></Field><div className="form-grid"><Field label="Эх сурвалж"><select name="source" defaultValue={lead?.source||'Facebook'}>{[...new Set([...sources,...(lead?[lead.source]:[])])].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Хариуцагч"><select name="owner" defaultValue={lead?.owner||me.email}>{lead?.owner==='__sheet_unassigned__'&&<option value="__sheet_unassigned__">Хуваарилалт хүлээж буй</option>}{members.filter(m=>m.active||m.email===lead?.owner).map(m=><option value={m.email} key={m.email} disabled={!m.active}>{m.name}{!m.active?' (идэвхгүй)':''}</option>)}</select></Field></div><Field label="Төлөв"><select name="status" defaultValue={lead?.status||'new'}>{Object.entries(stages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><div className="form-grid"><Field label="Дараагийн тов (УБ цаг)"><Input name="next_at" type="datetime-local" defaultValue={localInput(lead?lead.next_at:new Date(Date.now()+5*60000).toISOString())}/></Field><Field label="Дараагийн үйлдэл"><Input name="next_action" maxLength={200} defaultValue={lead?.next_action||'Эхний дуудлага'} placeholder="Товлосон ажил"/></Field></div><p className="form-help">Идэвхтэй хүсэлтэд хариуцагч, тов, дараагийн үйлдэл заавал байна. Худалдан авсан, татгалзсан, буруу дугаар төлөвт тов хаагдана.</p><Button type="submit" className="primary full" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Check size={16}/>}Хүсэлт хадгалах</Button></form>;}
function ActivityForm({lead,busy,onSubmit}:{lead:Lead;busy:boolean;onSubmit:(d:unknown)=>Promise<unknown>}){const [kind,setKind]=useState(lead.blocked||closed.includes(lead.status)?'note':'connected');const blocked=!!lead.blocked||closed.includes(lead.status);return <form className="form-stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const r=await onSubmit({kind,note:f.get('note'),next_at:fromInput(String(f.get('next_at')||'')),next_action:f.get('next_action')});if(r)form.reset();}}><div className="next-box"><Clock size={18}/><div><strong>{lead.blocked?'Холбоо барихгүй':dateLabel(lead.next_at)}</strong><p>{lead.next_action}</p></div></div><Field label="Хийсэн үйлдэл"><select value={kind} onChange={e=>setKind(e.target.value)}>{['connected','no_answer','message','note'].map(k=><option value={k} key={k} disabled={k!=='note'&&(blocked||(k==='no_answer'&&(lead.attempts||0)>=3))}>{kinds[k]}</option>)}</select></Field><Field label="Үр дүн, тохиролцоо *"><textarea name="note" required maxLength={2000} rows={4} placeholder="Юу ярилцсан, ямар шийдвэрт хүрсэн бэ?"/></Field><Field label="Дараагийн тов (УБ цаг)"><Input type="datetime-local" name="next_at" required={kind==='connected'} min={localInput(new Date().toISOString())}/></Field><Field label="Дараагийн үйлдэл"><Input name="next_action" required={kind==='connected'} maxLength={200} placeholder="Жишээ: үнийн санал танилцуулах"/></Field><p className="form-help">Хариу аваагүй бол дараагийн дуудлага 2, дараа нь 3 хоногийн дараа товлогдоно. Гурав дахь хариу аваагүй дуудлагад зогсоно. SMS, Messenger-ийг энд зөвхөн бүртгэнэ.</p><Button className="primary full" disabled={busy||(blocked&&kind!=='note')}><Plus size={16}/>Үйлдэл бүртгэх</Button></form>;}
function Optout({disabled,onConfirm}:{disabled:boolean;onConfirm:(note:string)=>Promise<unknown>}){const [open,setOpen]=useState(false);return <><Button variant="outline" disabled={disabled} onClick={()=>setOpen(true)}><Ban size={16}/>Холбоо барихгүй</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Дахин холбоо барихыг зогсоох</DialogTitle><DialogDescription>Энэ дугаарт бүх ажилтны давтан дуудлага, мессежийн бүртгэлийг хаана. Түүх хадгалагдана.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await onConfirm(String(f.get('note'))))setOpen(false);}}><Field label="Харилцагчийн хүсэлт / шалтгаан"><textarea required name="note" rows={3} maxLength={1000}/></Field><Button variant="destructive" disabled={disabled}>Дахин холбоо барихгүй гэж тэмдэглэх</Button></form></DialogContent></Dialog></>;}
function ImportDialog({open,onOpenChange,me,busy,submit}:{open:boolean;onOpenChange:(v:boolean)=>void;me:Member;busy:boolean;submit:(rows:unknown[])=>Promise<void>}){const [rows,setRows]=useState<Record<string,unknown>[]>([]),[error,setError]=useState('');const headers=['name','phone','product','source'];return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Хүсэлтүүдийг CSV-ээс оруулах</DialogTitle><DialogDescription>Нэг удаад 100 хүртэл хүсэлт. Ижил дугаарын бүртгэлийг алгасана.</DialogDescription></DialogHeader><Button variant="outline" onClick={()=>download('AntMall-import-template.csv','name,phone,product,source\r\n')}><Download size={16}/>Хоосон загвар татах</Button><Field label="UTF-8 CSV файл сонгох"><Input type="file" accept=".csv,text/csv" onChange={async e=>{setRows([]);setError('');const f=e.target.files?.[0];if(!f)return;try{if(f.size>150000)throw new Error('Файлын хэмжээ 150 KB-аас бага байна.');const parsed=parseCSV((await f.text()).replace(/^\uFEFF/,''));if(!parsed.length||headers.some(h=>!parsed[0].includes(h)))throw new Error('Баганын нэр: name, phone, product, source байх ёстой.');if(parsed.length>101)throw new Error('100 хүртэл мөр сонгоно уу.');const mapped=parsed.slice(1).map((r,i)=>{const d=Object.fromEntries(headers.map(h=>[h,r[parsed[0].indexOf(h)]?.trim()||'']));if(!d.name||!d.product||!d.source)throw new Error(`${i+2}-р мөрийн нэр, бүтээгдэхүүн, суваг дутуу.`);return {...d,phone:normalizePhone(d.phone),owner:me.email,status:'new',next_at:new Date(Date.now()+5*60000).toISOString(),next_action:'Импортын эхний дуудлага'};});setRows(mapped);}catch(e){setError((e as Error).message);}}}/></Field><p className="form-help">Нэр → name · Утас → phone · Бүтээгдэхүүн → product · Суваг → source. Импортын хүсэлтүүд танд хуваарилагдаж, 5 минутын дараа эхний дуудлага хийхээр товлогдоно.</p>{error&&<div role="alert" className="error-box">{error}</div>}{!!rows.length&&<><div className="import-preview"><Table><TableHeader><TableRow><TableHead>Нэр</TableHead><TableHead>Утас</TableHead><TableHead>Бүтээгдэхүүн</TableHead></TableRow></TableHeader><TableBody>{rows.slice(0,5).map((r,i)=><TableRow key={i}><TableCell>{String(r.name)}</TableCell><TableCell>{String(r.phone)}</TableCell><TableCell>{String(r.product)}</TableCell></TableRow>)}</TableBody></Table></div><p>{rows.length} мөр бэлэн · эхний 5 мөрийг харуулав</p><Button className="primary" disabled={busy} onClick={()=>submit(rows)}>{busy?<Loader2 className="spin" size={16}/>:<Upload size={16}/>}Шалгаад бүртгэх</Button></>}</DialogContent></Dialog>;}
function Guide(){return <div className="guide-grid"><section className="panel"><div className="eyebrow">01 / ӨДӨР ТУТМЫН АЖИЛ</div><h2>Хүсэлт бүрийг дараагийн алхамтай үлдээ.</h2><ol className="steps"><li><b>Өнөөдрийн ажлаа нээ.</b><p>Тов нь болсон хүсэлтүүдийг хяна. Шинээр ирсэн хүсэлтэд ажлын цагаар 5 минутаас өмнө хариу өгөхийг зорь.</p></li><li><b>Хүсэлтийн түүхийг эхэлж унш.</b><p>Бүтээгдэхүүн, төлөв, өмнөх дуудлага, хариуцагчийг тулга. Давхар дуудлага бүү хий.</p></li><li><b>Үр дүнгээ даруй бүртгэ.</b><p>Холбогдсон дуудлага, хариу аваагүй оролдлого, илгээсэн мессеж эсвэл тэмдэглэл сонго. Систем өөрөө мессеж илгээхгүй.</p></li><li><b>Тохиролцсон товоо хадгал.</b><p>Улаанбаатарын цагаар өдөр, цаг болон хийх үйлдлээ оруул. Худалдан авалт, татгалзалт, буруу дугаар бол төлөвөө хаа.</p></li></ol></section><section className="panel"><div className="eyebrow">02 / RECYCLE ХӨТӨЛБӨР</div><h2>Нэг мөчлөг. 14 хоног.</h2><div className="cadence"><div><b>D0</b><p>Эхний дуудлага. Хариу аваагүй бол нэг тайлбар мессежийг гаднын сувгаар илгээж бүртгэ.</p></div><div><b>D2</b><p>Хоёр дахь дуудлага. Өмнөх 14 хоногийн оролдлого давхар тооцогдоно.</p></div><div><b>D5</b><p>Гурав дахь оролдлого. 3 удаа хариу аваагүй бол тов автоматаар зогсоно.</p></div><div><b>D7–14</b><p>Зөвхөн холбогдож, сонирхол баталсан харилцагчид тохиролцсон сануулгыг гараар товло.</p></div></div><div className="notice compact"><Ban size={20}/><p>Татгалзсан, худалдан авсан, буруу дугаар, холбоо барихгүй хүсэлтэд үргэлжлүүлэхгүй. Хариуцагч солиход оролдлогын тоо тэглэхгүй.</p></div></section><section className="panel"><div className="eyebrow">03 / ХАРИУЦЛАГА БА ЭРХ</div><h2>Хэн юуг удирдах вэ?</h2><Table><TableBody><TableRow><TableCell><b>Борлуулалт</b></TableCell><TableCell>Өөрийн хүсэлт, түүх, тов, үйлдэл.</TableCell></TableRow><TableRow><TableCell><b>Удирдлага</b></TableCell><TableCell>Бүх хүсэлт, хуваарилалт, тайлан.</TableCell></TableRow><TableRow><TableCell><b>Админ</b></TableCell><TableCell>Дээрх эрхүүд болон гишүүний эрхийн удирдлага.</TableCell></TableRow></TableBody></Table><p className="form-help">Өдрийн төгсгөлд хоцорсон тов, хариуцагчгүй ажил, бүртгээгүй үр дүнг хянана. Энэ хувилбарын гишүүн нэмэх үйлдэл и-мэйл урилга илгээхгүй.</p></section><section className="panel"><div className="eyebrow">04 / ХАРИЛЦААНЫ ЖИШЭЭ</div><h2>Товч, ойлгомжтой, зөвшөөрөлтэй.</h2><blockquote>“Сайн байна уу, AntMall-аас холбогдож байна. Та өмнө нь [бүтээгдэхүүн]-ийг сонирхсон. Одоо ярилцахад тохиромжтой юу?”</blockquote><p className="muted">Хэрэв сонирхол хэвээр бол хэрэгцээ, боломжит хугацаа, дараагийн алхмыг тохиролц. Боломжгүй үед нь харилцагчийн хүссэн товыг сонго.</p><p className="muted">Дахин холбогдохгүй гэвэл шалтгааныг тэмдэглэн, хүсэлтийн “Холбоо барихгүй” үйлдлийг ашигла.</p></section></div>;}
