'use client';
import {Field} from '@/components/form-field';
import {GuardedForm,markFormSaved,markFormError} from '@/components/draft-guard';
import {useRemote} from '@/hooks/use-remote';
import {AsyncStatus} from '@/components/async-status';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Plus,Search,Loader2,ArrowUpRight,ClipboardList,Clock,CheckCircle2,CalendarDays,List,ChartNoAxesCombined,Wallet} from 'lucide-react';
import MonthCalendar, {type CalEvent} from './month-calendar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {inventoryStages,inventoryClosed,inventoryCategories,dateLabel,localInput,fromInput,type Member,type InventoryCount,type InventoryCountActivity} from '@/lib/crm';
type Stats={total:number;active:number;overdue:number;done:number};
type InventoryReport={total:number;byStatus:{status:string;count:number}[];byCategory:{category:string;count:number}[];byOwner:{owner:string;total:number;done:number}[];amounts:{expected:number;actual:number;counted:number;discrepancy:number}};
const todayUB=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
const ubDay=(iso:string)=>new Date(new Date(iso).getTime()+8*3600000).toISOString().slice(0,10);
async function api(body:unknown){const form=document.activeElement?.closest('form')||null;const r=await fetch('/api/inventory-counts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {fieldErrors?:Record<string,string>;error?:string;id?:string};if(!r.ok){markFormError(form,d.error||'Хүсэлт амжилтгүй.',d.fieldErrors);throw new Error(d.error||'Хүсэлт амжилтгүй.');}markFormSaved(form);return d;}
function TaskForm({task,members,busy,onSubmit}:{task?:InventoryCount;members:Member[];busy:boolean;onSubmit:(d:unknown)=>unknown}){
 return <GuardedForm className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const actual=String(f.get('actual_amount')||'').trim();onSubmit({title:f.get('title'),category:f.get('category'),owner:f.get('owner'),status:f.get('status'),due_at:fromInput(String(f.get('due_at')||'')),expected_amount:Number(f.get('expected_amount'))||0,actual_amount:actual===''?null:Number(actual),note:f.get('note')});}}>
 <Field label="Тооллогын нэр *"><Input name="title" required maxLength={160} defaultValue={task?.title} placeholder="Жишээ: 9-р сарын кассын тооллого"/></Field>
 <div className="form-grid"><Field label="Ангилал"><select name="category" defaultValue={task?.category||inventoryCategories[0]}>{inventoryCategories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Хариуцагч"><select name="owner" defaultValue={task?.owner||members[0]?.email}>{members.map(m=><option key={m.email} value={m.email} disabled={!m.active}>{m.name}{!m.active?' (идэвхгүй)':''}</option>)}</select></Field></div>
 <div className="form-grid"><Field label="Төлөв"><select name="status" defaultValue={task?.status||'planned'}>{Object.entries(inventoryStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Товлосон огноо (УБ цаг)"><Input name="due_at" type="datetime-local" defaultValue={localInput(task?task.due_at:null)}/></Field></div>
 <div className="form-grid"><Field label="Хүлээгдэж буй дүн (дэвтэр)"><Input name="expected_amount" type="number" min={0} max={1000000000000} defaultValue={task?.expected_amount??0}/></Field><Field label="Бодит тоолсон дүн"><Input name="actual_amount" type="number" min={0} max={1000000000000} defaultValue={task?.actual_amount??''} placeholder="Тоолсны дараа бөглөнө"/></Field></div>
 <Field label="Тайлбар"><textarea name="note" rows={3} maxLength={2000} defaultValue={task?.note||''} placeholder="Тооллогын дэлгэрэнгүй, байршил, оролцогчид…"/></Field>
 <Button type="submit" className="primary full" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Plus size={16}/>}Хадгалах</Button>
 </GuardedForm>;
}
export default function InventoryCountsPanel({me,members}:{me:Member;members:Member[]}){
 const [items,setItems]=useState<InventoryCount[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[stats,setStats]=useState<Stats|null>(null);
 const [create,setCreate]=useState(false),[busy,setBusy]=useState(false);
 const [detailId,setDetailId]=useState(''),[detail,setDetail]=useState<{task:InventoryCount;activities:InventoryCountActivity[]}|null>(null),[detailError,setDetailError]=useState('');
 const [mode,setMode]=useState<'list'|'calendar'|'report'>('list'),[calMonth,setCalMonth]=useState(()=>todayUB().slice(0,7));
 const [reportFrom,setReportFrom]=useState(''),[reportTo,setReportTo]=useState(''),[retryReport,setRetryReport]=useState(0);
 const seq=useRef(0),detailSeq=useRef(0);
 const activeMembers=members.filter(m=>m.active);
 const load=useCallback(async()=>{const n=++seq.current;setLoading(true);try{const r=await fetch('/api/inventory-counts?'+new URLSearchParams({status,q,page:String(page)}),{cache:'no-store'});const d=await r.json() as {items?:InventoryCount[];count?:number;stats?:Stats;error?:string};if(!r.ok)throw new Error(d.error);if(n===seq.current){setItems(d.items||[]);setCount(d.count||0);setStats(d.stats||null);setError('');}}catch(e){if(n===seq.current)setError((e as Error).message);}finally{if(n===seq.current)setLoading(false);}},[status,q,page]);
 useEffect(()=>{const t=setTimeout(load,q?250:0);return()=>clearTimeout(t);},[load,q]);
 // Календарь горим: тухайн сард due_at тохирох хөнгөн жагсаалт (одоогийн шүүлтүүрээр хязгаарлагдсан).
 const calUrl='/api/inventory-counts?'+new URLSearchParams({calendar:'1',month:calMonth,q,status});
 const calendar=useRemote<{items:{id:string;title:string;due_at:string;status:string;day_count:number}[]}>(mode==='calendar'?calUrl:null);
 const calLoading=calendar.loading;
 const calEvents:CalEvent[]=(calendar.data?.items||[]).map(t=>({id:t.id,date:ubDay(t.due_at),label:t.title,dayCount:t.day_count}));
 // Тайлан горим: сонгосон хугацааны (rfrom/rto) төлөв/ангилал/хариуцагч, хүлээгдэж буй/бодит дүнгийн задаргаа.
 const reportState=useRemote<InventoryReport>(mode==='report'?'/api/inventory-counts?'+new URLSearchParams({report:'1',rfrom:reportFrom,rto:reportTo,retry:String(retryReport)}):null);
 const report=reportState.data,reportLoading=reportState.loading;
 const openTask=useCallback(async(id:string)=>{const n=++detailSeq.current;setDetailId(id);setDetail(null);setDetailError('');try{const r=await fetch('/api/inventory-counts?id='+encodeURIComponent(id),{cache:'no-store'});const d=await r.json() as {task?:InventoryCount;activities?:InventoryCountActivity[];error?:string};if(!r.ok)throw new Error(d.error);if(n===detailSeq.current)setDetail(d as {task:InventoryCount;activities:InventoryCountActivity[]});}catch(e){if(n===detailSeq.current)setDetailError((e as Error).message);}},[]);
 const mutate=async(body:unknown)=>{setBusy(true);try{const r=await api(body);toast.success('Амжилттай хадгаллаа');void load();if(detailId)await openTask(detailId);return r;}catch(e){toast.error((e as Error).message);return null;}finally{setBusy(false);}};
 const overdue=(t:InventoryCount)=>!!t.due_at&&t.due_at<new Date().toISOString()&&!inventoryClosed.includes(t.status);
 const ownerName=(email:string)=>members.find(m=>m.email===email)?.name||email;
 const totalPages=Math.max(1,Math.ceil(count/50));
 const reportActive=report?report.byStatus.filter(b=>!inventoryClosed.includes(b.status)).reduce((n,b)=>n+b.count,0):0;
 const reportDone=report?.byStatus.find(b=>b.status==='done')?.count||0;
 return <section className="table-panel">
 {mode==='report'&&<div className="report-range panel"><Field label="Хугацааны эхлэл (үүсгэсэн огноо)"><Input type="date" value={reportFrom} max={reportTo||undefined} onChange={e=>setReportFrom(e.target.value)}/></Field><Field label="Хугацааны төгсгөл"><Input type="date" value={reportTo} min={reportFrom||undefined} onChange={e=>setReportTo(e.target.value)}/></Field>{(reportFrom||reportTo)&&<Button variant="ghost" size="sm" onClick={()=>{setReportFrom('');setReportTo('');}}>Бүх хугацаа</Button>}<p className="muted text-sm">{reportState.error?'Тайлан ачаалагдаагүй.':reportLoading?'Тайлан ачаалж байна…':reportFrom||reportTo?`${reportFrom||'…'} — ${reportTo||'өнөөдөр'} хооронд үүсгэсэн ${(report?.total||0).toLocaleString()} тооллогод үндэслэв.`:'Бүх хугацааны мэдээлэл харагдаж байна. Тодорхой үе харахын тулд огноо сонгоно уу.'}</p></div>}
 {mode==='report'?report&&<div className="metrics"><div className="metric"><div><span>Нийт тооллого</span><ClipboardList size={19}/></div><strong>{report.total.toLocaleString()}</strong><small>Сонгосон хугацаанд үүсгэсэн</small></div><div className="metric metric-focus"><div><span>Идэвхтэй</span><Clock size={19}/></div><strong>{reportActive.toLocaleString()}</strong><small>Хийгдэж/төлөвлөгдөж буй</small></div><div className={'metric'+(stats?.overdue?' metric-alert':'')}><div><span>Хугацаа хэтэрсэн</span><Clock size={19}/></div><strong>{(stats?.overdue||0).toLocaleString()}</strong><small>Одоогийн байдлаар, бүх хугацаа</small></div><div className="metric"><div><span>Дууссан</span><CheckCircle2 size={19}/></div><strong>{reportDone.toLocaleString()}</strong><small>Энэ хугацаанд үүссэнээс одоо дууссан</small></div></div>:stats&&<div className="metrics"><div className="metric"><div><span>Нийт тооллого</span><ClipboardList size={19}/></div><strong>{stats.total.toLocaleString()}</strong><small>Бүх санхүүгийн тооллого</small></div><div className="metric metric-focus"><div><span>Идэвхтэй</span><Clock size={19}/></div><strong>{stats.active.toLocaleString()}</strong><small>Хийгдэж/төлөвлөгдөж буй</small></div><div className={'metric'+(stats.overdue?' metric-alert':'')}><div><span>Хугацаа хэтэрсэн</span><Clock size={19}/></div><strong>{stats.overdue.toLocaleString()}</strong><small>Товлосон хугацаа өнгөрсөн</small></div><div className="metric"><div><span>Дууссан</span><CheckCircle2 size={19}/></div><strong>{stats.done.toLocaleString()}</strong><small>Хаагдсан тооллого</small></div></div>}
 <div className="table-toolbar"><h2>Санхүүгийн тооллого<span>{count}</span></h2><div className="row"><Button className="primary" size="sm" onClick={()=>setCreate(true)}><Plus size={16}/>Шинэ тооллого</Button><div className="view-toggle"><Button variant={mode==='list'?'default':'outline'} className={mode==='list'?'primary':''} size="sm" onClick={()=>setMode('list')}><List size={14}/>Жагсаалт</Button><Button variant={mode==='calendar'?'default':'outline'} className={mode==='calendar'?'primary':''} size="sm" onClick={()=>setMode('calendar')}><CalendarDays size={14}/>Календарь</Button><Button variant={mode==='report'?'default':'outline'} className={mode==='report'?'primary':''} size="sm" onClick={()=>setMode('report')}><ChartNoAxesCombined size={14}/>Тайлан</Button></div></div></div>
 <div className="filters">{mode!=='report'&&<><div className="search"><Search size={17}/><Input aria-label="Тооллого хайх" placeholder="Нэрээр хайх…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><select aria-label="Төлөвөөр шүүх" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Бүх төлөв</option>{Object.entries(inventoryStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></>}{(loading||calLoading||reportLoading)&&<Loader2 size={17} className="spin muted"/>}</div>
 {error&&<div role="alert" className="error-box">{error} <button onClick={load}>Дахин оролдох</button></div>}
 {mode==='calendar'?<MonthCalendar month={calMonth} onMonthChange={setCalMonth} events={calEvents} onOpen={openTask} todayDate={todayUB()} loading={calLoading} error={calendar.error} onRetry={calendar.retry} endpoint={calUrl} key={calUrl}/>:mode==='report'?(reportState.error||reportLoading)?<AsyncStatus error={reportState.error} loading={reportLoading} retry={()=>setRetryReport(n=>n+1)}/>:<div className="reports-grid">
 <section className="panel team-report"><div className="eyebrow">ТӨЛӨВ</div><h2>Төлөвийн задаргаа</h2><p className="muted">Төлөв бүрийн тооллогын тоо, сонгосон хугацаанд эзлэх хувь.</p><div className="bars">{Object.entries(inventoryStages).map(([k,v])=>{const c=report?.byStatus.find(b=>b.status===k)?.count||0;const pct=report?.total?Math.round(c/report.total*100):0;return <div className="bar-row" key={k}><div><span>{v}</span><strong>{c} <small>({pct}%)</small></strong></div><div className="bar-track"><span style={{width:pct+'%'}}/></div></div>;})}</div></section>
 <section className="panel team-report"><div className="eyebrow">АНГИЛАЛ</div><h2>Ангилалаар хуваарилалт</h2><p className="muted">Ангилал тус бүрийн тооллогын тоо, сонгосон хугацаанд эзлэх хувь.</p><div className="bars">{inventoryCategories.map(c=>{const cnt=report?.byCategory.find(b=>b.category===c)?.count||0;const pct=report?.total?Math.round(cnt/report.total*100):0;return <div className="bar-row" key={c}><div><span>{c}</span><strong>{cnt} <small>({pct}%)</small></strong></div><div className="bar-track"><span style={{width:pct+'%'}}/></div></div>;})}</div></section>
 <section className="panel team-report"><div className="eyebrow">ДҮНГИЙН ЗӨРҮҮ</div><h2>Хүлээгдэж буй ба бодит дүн</h2><p className="muted">Сонгосон хугацаанд бүртгэгдсэн тооллогын дэвтэр дэх ба бодит тоолсон дүн.</p><div className="budget-cards"><div className="metric"><div><span>Хүлээгдэж буй дүн</span><Wallet size={19}/></div><strong>{(report?.amounts.expected||0).toLocaleString()}₮</strong></div><div className="metric"><div><span>Бодит тоолсон дүн</span><CheckCircle2 size={19}/></div><strong>{(report?.amounts.actual||0).toLocaleString()}₮</strong><small>{report?.amounts.counted||0} тооллого тоологдсон</small></div><div className={'metric'+((report?.amounts.discrepancy||0)!==0?' metric-alert':'')}><div><span>Зөрүү</span><Wallet size={19}/></div><strong>{(report?.amounts.discrepancy||0).toLocaleString()}₮</strong></div></div></section>
 <section className="panel team-report"><div className="eyebrow">БАГИЙН ГИШҮҮД</div><h2>Ажилтан тус бүрийн үзүүлэлт</h2><p className="muted">Сонгосон хугацаанд хариуцсан тооллого, дууссан тоо, гүйцэтгэлийн хувь.</p><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>АЖИЛТАН</TableHead><TableHead>НИЙТ</TableHead><TableHead>ДУУССАН</TableHead><TableHead>ГҮЙЦЭТГЭЛ</TableHead></TableRow></TableHeader><TableBody>{[...(report?.byOwner||[])].sort((a,b)=>b.total-a.total).map(r=><TableRow key={r.owner}><TableCell><strong>{ownerName(r.owner)}</strong><small>{r.owner}</small></TableCell><TableCell>{r.total}</TableCell><TableCell>{r.done}</TableCell><TableCell>{r.total?(r.done/r.total*100).toFixed(1):'0.0'}%</TableCell></TableRow>)}{!report?.byOwner.length&&<TableRow><TableCell colSpan={4} className="muted">Сонгосон хугацаанд тооллого алга.</TableCell></TableRow>}</TableBody></Table></div></section>
 </div>:<>
 {items.length?<div className="table-scroll"><Table><TableHeader><TableRow><TableHead>НЭР</TableHead><TableHead>АНГИЛАЛ</TableHead><TableHead>ХАРИУЦАГЧ</TableHead><TableHead>ТӨЛӨВ</TableHead><TableHead>ДҮН (ХҮЛЭЭГДЭЖ/БОДИТ)</TableHead><TableHead>ТОВЛОСОН ОГНОО</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(t=><TableRow key={t.id} className={'lead-row'+(overdue(t)?' overdue-row':'')}><TableCell><button className="lead-link" onClick={()=>openTask(t.id)}><span className="lead-avatar"><ClipboardList size={16}/></span><strong>{t.title}</strong></button></TableCell><TableCell>{t.category}</TableCell><TableCell><span className="owner-label">{ownerName(t.owner)}</span></TableCell><TableCell><span className={'stage '+(inventoryClosed.includes(t.status)?(t.status==='done'?'stage-won':'stage-lost'):'stage-pending')}>{inventoryStages[t.status]||t.status}</span></TableCell><TableCell>{t.expected_amount.toLocaleString()} / {t.actual_amount===null?'—':t.actual_amount.toLocaleString()}</TableCell><TableCell><div className={overdue(t)?'due-text':''}>{t.due_at?dateLabel(t.due_at):'Товгүй'}</div></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={t.title+' нээх'} onClick={()=>openTask(t.id)}><ArrowUpRight size={18}/></Button></TableCell></TableRow>)}</TableBody></Table></div>:!loading&&<p className="muted chat-empty-list">Тооллого бүртгэгдээгүй байна.</p>}
 {totalPages>1&&<div className="table-footer"><span>{count} тооллого</span><div className="row"><Button size="sm" variant="outline" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Өмнөх</Button><span className="muted">{page} / {totalPages}</span><Button size="sm" variant="outline" disabled={page>=totalPages||loading} onClick={()=>setPage(p=>p+1)}>Дараах</Button></div></div>}
 </>}
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Шинэ тооллого</DialogTitle><DialogDescription>Тооллогын мэдээлэл, хариуцагч, товлосон огноог тохируулна уу.</DialogDescription></DialogHeader><TaskForm members={activeMembers.length?activeMembers:[me]} busy={busy} onSubmit={async d=>{const r=await mutate({action:'create',data:d});if(r)setCreate(false);}}/></DialogContent></Dialog>
 <Sheet open={!!detailId} onOpenChange={o=>{if(!o){detailSeq.current++;setDetailId('');setDetail(null);}}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{detail?.task.title||'Тооллогын дэлгэрэнгүй'}</SheetTitle><SheetDescription>{detail?`${detail.task.category} · ${inventoryStages[detail.task.status]||detail.task.status}`:'Мэдээлэл болон явцын түүх'}</SheetDescription></SheetHeader>{detailError?<div className="error-box">{detailError}<Button onClick={()=>openTask(detailId)}>Дахин нээх</Button></div>:!detail?<div className="loading"><Loader2 className="spin"/>Ачаалж байна…</div>:<div className="detail-body">
 <div className="next-box"><Wallet size={18}/><div><strong>Хүлээгдэж буй: {detail.task.expected_amount.toLocaleString()}₮</strong><p>Бодит: {detail.task.actual_amount===null?'Тоологдоогүй':detail.task.actual_amount.toLocaleString()+'₮'} · Хариуцагч: {ownerName(detail.task.owner)}</p></div></div>
 <TaskForm key={detail.task.version} task={detail.task} members={activeMembers.length?activeMembers:[me]} busy={busy} onSubmit={d=>mutate({action:'update',id:detail.task.id,version:detail.task.version,data:d})}/>
 <div className="detail-tools"><GuardedForm className="form-stack full" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const note=String(f.get('note')||'').trim();if(!note)return;const r=await mutate({action:'activity',id:detail.task.id,version:detail.task.version,data:{note}});if(r){form.reset();markFormSaved(form);}}}><Field label="Явцын тэмдэглэл нэмэх"><textarea name="note" required maxLength={2000} rows={2} placeholder="Юу хийсэн, ямар үр дүнтэй болсныг тэмдэглэ…"/></Field><Button className="primary full" disabled={busy}><Plus size={16}/>Тэмдэглэл бүртгэх</Button></GuardedForm></div>
 <div className="timeline">{detail.activities.map(a=><article key={a.id}><span className="timeline-dot"/><div className="row between"><strong>{ownerName(a.actor)}</strong><time>{dateLabel(a.created_at)}</time></div><p>{a.note}</p></article>)}</div>
 </div>}</SheetContent></Sheet>
 </section>;
}
