'use client';
import {Field} from '@/components/form-field';
import {GuardedForm,markFormSaved,markFormError} from '@/components/draft-guard';
import {useRemote} from '@/hooks/use-remote';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Plus,Search,Loader2,ArrowUpRight,ClipboardList,Clock,CheckCircle2,CalendarDays,List,AlertTriangle} from 'lucide-react';
import MonthCalendar, {type CalEvent} from './month-calendar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {inventoryStages,inventoryClosed,dateLabel,localInput,fromInput,type Member,type InventoryCount,type InventoryCountActivity,type InventoryCountLine} from '@/lib/crm';
type Stats={total:number;active:number;overdue:number;done:number};
type Warehouse={id:string;name:string};
type ListRow=InventoryCount&{warehouse_name:string;line_count:number;discrepancy_count:number};
const todayUB=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
const ubDay=(iso:string)=>new Date(new Date(iso).getTime()+8*3600000).toISOString().slice(0,10);
async function api(body:unknown){const form=document.activeElement?.closest('form')||null;const r=await fetch('/api/inventory-counts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {fieldErrors?:Record<string,string>;error?:string;id?:string;adjusted?:number};if(!r.ok){markFormError(form,d.error||'Хүсэлт амжилтгүй.',d.fieldErrors);throw new Error(d.error||'Хүсэлт амжилтгүй.');}markFormSaved(form);return d;}
function TaskForm({task,warehouses,members,busy,onSubmit}:{task?:InventoryCount;warehouses:Warehouse[];members:Member[];busy:boolean;onSubmit:(d:unknown)=>unknown}){
 return <GuardedForm className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({title:f.get('title'),warehouse_id:f.get('warehouse_id'),owner:f.get('owner'),status:f.get('status'),due_at:fromInput(String(f.get('due_at')||'')),note:f.get('note')});}}>
 <Field label="Тооллогын нэр *"><Input name="title" required maxLength={160} defaultValue={task?.title} placeholder="Жишээ: Урд агуулахын 9-р сарын тооллого"/></Field>
 <div className="form-grid"><Field label="Агуулах *">{task?<Input value={warehouses.find(w=>w.id===task.warehouse_id)?.name||''} disabled/>:<select name="warehouse_id" required defaultValue="">{[<option key="" value="" disabled>Сонгох…</option>,...warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)]}</select>}{task&&<input type="hidden" name="warehouse_id" value={task.warehouse_id||''}/>}</Field><Field label="Хариуцагч"><select name="owner" defaultValue={task?.owner||members[0]?.email}>{members.map(m=><option key={m.email} value={m.email} disabled={!m.active}>{m.name}{!m.active?' (идэвхгүй)':''}</option>)}</select></Field></div>
 <div className="form-grid"><Field label="Төлөв"><select name="status" defaultValue={task?.status||'planned'}>{Object.entries(inventoryStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Товлосон огноо (УБ цаг)"><Input name="due_at" type="datetime-local" defaultValue={localInput(task?task.due_at:null)}/></Field></div>
 <Field label="Тайлбар"><textarea name="note" rows={3} maxLength={2000} defaultValue={task?.note||''} placeholder="Тооллогын дэлгэрэнгүй, байршил, оролцогчид…"/></Field>
 <Button type="submit" className="primary full" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Plus size={16}/>}Хадгалах</Button>
 </GuardedForm>;
}
export default function InventoryCountsPanel({me,members}:{me:Member;members:Member[]}){
 const [items,setItems]=useState<ListRow[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[stats,setStats]=useState<Stats|null>(null);
 const [warehouses,setWarehouses]=useState<Warehouse[]>([]);
 const [create,setCreate]=useState(false),[busy,setBusy]=useState(false);
 const [detailId,setDetailId]=useState(''),[detail,setDetail]=useState<{task:InventoryCount;activities:InventoryCountActivity[];lines:InventoryCountLine[];warehouse_name:string}|null>(null),[detailError,setDetailError]=useState('');
 const [counted,setCounted]=useState<Record<string,string>>({});
 const [mode,setMode]=useState<'list'|'calendar'>('list'),[calMonth,setCalMonth]=useState(()=>todayUB().slice(0,7));
 const seq=useRef(0),detailSeq=useRef(0);
 const activeMembers=members.filter(m=>m.active);
 const load=useCallback(async()=>{const n=++seq.current;setLoading(true);try{const r=await fetch('/api/inventory-counts?'+new URLSearchParams({status,q,page:String(page)}),{cache:'no-store'});const d=await r.json() as {items?:ListRow[];count?:number;stats?:Stats;error?:string};if(!r.ok)throw new Error(d.error);if(n===seq.current){setItems(d.items||[]);setCount(d.count||0);setStats(d.stats||null);setError('');}}catch(e){if(n===seq.current)setError((e as Error).message);}finally{if(n===seq.current)setLoading(false);}},[status,q,page]);
 useEffect(()=>{const t=setTimeout(load,q?250:0);return()=>clearTimeout(t);},[load,q]);
 useEffect(()=>{fetch('/api/inventory?view=warehouses',{cache:'no-store'}).then(r=>r.json()).then(d=>setWarehouses(d.items||[])).catch(()=>{});},[]);
 // Календарь горим: тухайн сард due_at тохирох хөнгөн жагсаалт (одоогийн шүүлтүүрээр хязгаарлагдсан).
 const calUrl='/api/inventory-counts?'+new URLSearchParams({calendar:'1',month:calMonth,q,status});
 const calendar=useRemote<{items:{id:string;title:string;due_at:string;status:string;day_count:number}[]}>(mode==='calendar'?calUrl:null);
 const calLoading=calendar.loading;
 const calEvents:CalEvent[]=(calendar.data?.items||[]).map(t=>({id:t.id,date:ubDay(t.due_at),label:t.title,dayCount:t.day_count}));
 const openTask=useCallback(async(id:string)=>{const n=++detailSeq.current;setDetailId(id);setDetail(null);setDetailError('');setCounted({});try{const r=await fetch('/api/inventory-counts?id='+encodeURIComponent(id),{cache:'no-store'});const d=await r.json() as {task?:InventoryCount;activities?:InventoryCountActivity[];lines?:InventoryCountLine[];warehouse_name?:string;error?:string};if(!r.ok)throw new Error(d.error);if(n===detailSeq.current){setDetail(d as {task:InventoryCount;activities:InventoryCountActivity[];lines:InventoryCountLine[];warehouse_name:string});const init:Record<string,string>={};for(const l of d.lines||[])if(l.counted_qty!==null)init[l.id]=String(l.counted_qty);setCounted(init);}}catch(e){if(n===detailSeq.current)setDetailError((e as Error).message);}},[]);
 const mutate=async(body:unknown)=>{setBusy(true);try{const r=await api(body);toast.success('Амжилттай хадгаллаа');void load();if(detailId)await openTask(detailId);return r;}catch(e){toast.error((e as Error).message);return null;}finally{setBusy(false);}};
 // Тоолсон дүнг серверт илгээх: хоосон үлдээсэн мөрийг "тоологдоогүй" (null) гэж үзнэ.
 const linePayload=(d:{lines:InventoryCountLine[]})=>d.lines.map(l=>({line_id:l.id,counted_qty:counted[l.id]===undefined||counted[l.id]===''?null:Math.max(0,Math.round(Number(counted[l.id])||0))}));
 const saveLines=async()=>{if(!detail)return;await mutate({action:'save_lines',id:detail.task.id,version:detail.task.version,data:{lines:linePayload(detail)}});};
 // Эхлээд тоолсон дүнг хадгалснаар version 1-ээр өснө; finalize-д тэр шинэ version-ийг дамжуулна.
 const finalize=async()=>{if(!detail)return;setBusy(true);try{
  const id=detail.task.id;
  await api({action:'save_lines',id,version:detail.task.version,data:{lines:linePayload(detail)}});
  const r=await api({action:'finalize',id,version:detail.task.version+1,data:{}});
  toast.success(`Тооллого дууслаа. ${r.adjusted||0} бараанд зөрүү тохируулав.`);
  void load();await openTask(id);
 }catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const overdue=(t:InventoryCount)=>!!t.due_at&&t.due_at<new Date().toISOString()&&!inventoryClosed.includes(t.status);
 const ownerName=(email:string)=>members.find(m=>m.email===email)?.name||email;
 const totalPages=Math.max(1,Math.ceil(count/50));
 return <section className="table-panel">
 {stats&&<div className="metrics"><div className="metric"><div><span>Нийт тооллого</span><ClipboardList size={19}/></div><strong>{stats.total.toLocaleString()}</strong><small>Бүх санхүүгийн тооллого</small></div><div className="metric metric-focus"><div><span>Идэвхтэй</span><Clock size={19}/></div><strong>{stats.active.toLocaleString()}</strong><small>Хийгдэж/төлөвлөгдөж буй</small></div><div className={'metric'+(stats.overdue?' metric-alert':'')}><div><span>Хугацаа хэтэрсэн</span><Clock size={19}/></div><strong>{stats.overdue.toLocaleString()}</strong><small>Товлосон хугацаа өнгөрсөн</small></div><div className="metric"><div><span>Дууссан</span><CheckCircle2 size={19}/></div><strong>{stats.done.toLocaleString()}</strong><small>Хаагдсан тооллого</small></div></div>}
 <div className="table-toolbar"><h2>Санхүүгийн тооллого<span>{count}</span></h2><div className="row"><Button className="primary" size="sm" onClick={()=>setCreate(true)} disabled={!warehouses.length}><Plus size={16}/>Шинэ тооллого</Button><div className="view-toggle"><Button variant={mode==='list'?'default':'outline'} className={mode==='list'?'primary':''} size="sm" onClick={()=>setMode('list')}><List size={14}/>Жагсаалт</Button><Button variant={mode==='calendar'?'default':'outline'} className={mode==='calendar'?'primary':''} size="sm" onClick={()=>setMode('calendar')}><CalendarDays size={14}/>Календарь</Button></div></div></div>
 {!warehouses.length&&<p className="muted" style={{padding:'0 23px 12px'}}>Эхлээд "Бараа" табаас дор хаяж нэг агуулах/салбар үүсгэнэ үү.</p>}
 <div className="filters"><div className="search"><Search size={17}/><Input aria-label="Тооллого хайх" placeholder="Нэрээр хайх…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><select aria-label="Төлөвөөр шүүх" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Бүх төлөв</option>{Object.entries(inventoryStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{(loading||calLoading)&&<Loader2 size={17} className="spin muted"/>}</div>
 {error&&<div role="alert" className="error-box">{error} <button onClick={load}>Дахин оролдох</button></div>}
 {mode==='calendar'?<div className="panel"><MonthCalendar month={calMonth} onMonthChange={setCalMonth} events={calEvents} onOpen={openTask} todayDate={todayUB()} loading={calLoading} error={calendar.error} onRetry={calendar.retry} endpoint={calUrl} key={calUrl}/></div>:<>
 {items.length?<div className="table-scroll"><Table><TableHeader><TableRow><TableHead>НЭР</TableHead><TableHead>АГУУЛАХ</TableHead><TableHead>ХАРИУЦАГЧ</TableHead><TableHead>ТӨЛӨВ</TableHead><TableHead>БАРАА</TableHead><TableHead>ЗӨРҮҮТЭЙ</TableHead><TableHead>ТОВЛОСОН ОГНОО</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(t=><TableRow key={t.id} className={'lead-row'+(overdue(t)?' overdue-row':'')}><TableCell><button className="lead-link" onClick={()=>openTask(t.id)}><span className="lead-avatar"><ClipboardList size={16}/></span><strong>{t.title}</strong></button></TableCell><TableCell>{t.warehouse_name||'—'}</TableCell><TableCell><span className="owner-label">{ownerName(t.owner)}</span></TableCell><TableCell><span className={'stage '+(inventoryClosed.includes(t.status)?(t.status==='done'?'stage-won':'stage-lost'):'stage-pending')}>{inventoryStages[t.status]||t.status}</span></TableCell><TableCell>{t.line_count.toLocaleString()}</TableCell><TableCell>{t.discrepancy_count>0?<span className="due-text">{t.discrepancy_count}</span>:'0'}</TableCell><TableCell><div className={overdue(t)?'due-text':''}>{t.due_at?dateLabel(t.due_at):'Товгүй'}</div></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={t.title+' нээх'} onClick={()=>openTask(t.id)}><ArrowUpRight size={18}/></Button></TableCell></TableRow>)}</TableBody></Table></div>:!loading&&<p className="muted chat-empty-list">Тооллого бүртгэгдээгүй байна.</p>}
 {totalPages>1&&<div className="table-footer"><span>{count} тооллого</span><div className="row"><Button size="sm" variant="outline" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Өмнөх</Button><span className="muted">{page} / {totalPages}</span><Button size="sm" variant="outline" disabled={page>=totalPages||loading} onClick={()=>setPage(p=>p+1)}>Дараах</Button></div></div>}
 </>}
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Шинэ тооллого</DialogTitle><DialogDescription>Агуулахыг сонгоход тухайн агуулахын одоогийн үлдэгдэлтэй бүх бараа автоматаар мөр болж орно.</DialogDescription></DialogHeader><TaskForm warehouses={warehouses} members={activeMembers.length?activeMembers:[me]} busy={busy} onSubmit={async d=>{const r=await mutate({action:'create',data:d});if(r)setCreate(false);}}/></DialogContent></Dialog>
 <Sheet open={!!detailId} onOpenChange={o=>{if(!o){detailSeq.current++;setDetailId('');setDetail(null);}}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{detail?.task.title||'Тооллогын дэлгэрэнгүй'}</SheetTitle><SheetDescription>{detail?`${detail.warehouse_name} · ${inventoryStages[detail.task.status]||detail.task.status}`:'Мэдээлэл болон явцын түүх'}</SheetDescription></SheetHeader>{detailError?<div className="error-box">{detailError}<Button onClick={()=>openTask(detailId)}>Дахин нээх</Button></div>:!detail?<div className="loading"><Loader2 className="spin"/>Ачаалж байна…</div>:<div className="detail-body">
 <div className="next-box"><ClipboardList size={18}/><div><strong>{detail.warehouse_name}</strong><p>Хариуцагч: {ownerName(detail.task.owner)} · {detail.lines.length} бараа</p></div></div>
 <TaskForm key={detail.task.version} task={detail.task} warehouses={warehouses} members={activeMembers.length?activeMembers:[me]} busy={busy} onSubmit={d=>mutate({action:'update',id:detail.task.id,version:detail.task.version,data:d})}/>
 <div className="section-heading"><div><h2>Барааны тооллого</h2><p className="muted">Хүлээгдэж буй тоо систем дэх үлдэгдэл; тоолсон дүнгээ бичээд хадгална уу.</p></div></div>
 <div className="table-scroll"><Table><TableHeader><TableRow><TableHead>БАРАА</TableHead><TableHead>ХҮЛЭЭГДЭЖ БУЙ</TableHead><TableHead>ТООЛСОН</TableHead><TableHead>ЗӨРҮҮ</TableHead></TableRow></TableHeader><TableBody>{detail.lines.map(l=>{const cv=counted[l.id];const cn=cv===undefined||cv===''?null:Number(cv)||0;const diff=cn===null?null:cn-l.expected_qty;return <TableRow key={l.id}><TableCell><strong>{l.item_name}</strong>{l.item_code&&<small>{l.item_code}</small>}</TableCell><TableCell>{l.expected_qty.toLocaleString()}</TableCell><TableCell><Input type="number" min={0} style={{maxWidth:100}} value={cv??''} onChange={e=>setCounted(c=>({...c,[l.id]:e.target.value}))} disabled={detail.task.status==='done'}/></TableCell><TableCell>{diff===null?'—':<span className={diff!==0?'due-text':undefined}>{diff>0?'+':''}{diff.toLocaleString()}</span>}</TableCell></TableRow>;})}{!detail.lines.length&&<TableRow><TableCell colSpan={4} className="muted">Энэ агуулахад тооллого хийх бараа алга.</TableCell></TableRow>}</TableBody></Table></div>
 {detail.task.status!=='done'&&<div className="row"><Button size="sm" onClick={saveLines} disabled={busy}>{busy?<Loader2 className="spin" size={15}/>:<CheckCircle2 size={15}/>}Тоолсон дүн хадгалах</Button><Button size="sm" variant="destructive" onClick={finalize} disabled={busy}><AlertTriangle size={15}/>Тооллого дуусгаж, зөрүүг тохируулах</Button></div>}
 <div className="detail-tools"><GuardedForm className="form-stack full" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const note=String(f.get('note')||'').trim();if(!note)return;const r=await mutate({action:'activity',id:detail.task.id,version:detail.task.version,data:{note}});if(r){form.reset();markFormSaved(form);}}}><Field label="Явцын тэмдэглэл нэмэх"><textarea name="note" required maxLength={2000} rows={2} placeholder="Юу хийсэн, ямар үр дүнтэй болсныг тэмдэглэ…"/></Field><Button className="primary full" disabled={busy}><Plus size={16}/>Тэмдэглэл бүртгэх</Button></GuardedForm></div>
 <div className="timeline">{detail.activities.map(a=><article key={a.id}><span className="timeline-dot"/><div className="row between"><strong>{ownerName(a.actor)}</strong><time>{dateLabel(a.created_at)}</time></div><p>{a.note}</p></article>)}</div>
 </div>}</SheetContent></Sheet>
 </section>;
}
