 'use client';
import {useState} from 'react';
import {Alert,Button,Card,Descriptions,Drawer,Empty,Input,Pagination,Progress,Segmented,Select,Space,Statistic,Table,Tag} from 'antd';
import type {ColumnsType} from 'antd/es/table';
import {useIsMobile} from '@/hooks/use-mobile';
import {stages} from '@/lib/crm';
export type MemberPerformance={email:string;name:string;total:number;counts:Record<string,number>;activities:number;direct_sales?:number;direct_amount?:number;sold_total?:number};
type Metric='sold'|'total'|'activities'|'conversion'|'amount';
const count=(n:number)=>n.toLocaleString('en-US');
const sold=(r:MemberPerformance)=>(r.counts.won||0)+(r.direct_sales||0);
const conversion=(r:MemberPerformance)=>r.total?(r.counts.won||0)/r.total*100:0;
const metrics:{value:Metric;label:string;unit:string}[]=[{value:'sold',label:'Нийт худалдан авалт',unit:'бүртгэл'},{value:'total',label:'Хүсэлтийн тоо',unit:'хүсэлт'},{value:'activities',label:'Бүртгэсэн үйлдэл',unit:'үйлдэл'},{value:'conversion',label:'Хүсэлтийн хөрвөлт',unit:'%'},{value:'amount',label:'Шууд борлуулалтын орлого',unit:'₮'}];
const metricValue=(r:MemberPerformance,m:Metric)=>m==='sold'?sold(r):m==='conversion'?conversion(r):m==='amount'?(r.direct_amount||0):r[m];
export default function TeamPerformance({rows,from,to}:{rows:MemberPerformance[];from:string;to:string}){
 const mobile=useIsMobile(),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[metric,setMetric]=useState<Metric>('sold'),[view,setView]=useState('list'),[page,setPage]=useState(1),[selected,setSelected]=useState<string|null>(null);
 const staff=rows.filter(r=>r.email!=='__sheet_unassigned__'),unassigned=rows.find(r=>r.email==='__sheet_unassigned__');
 const shown=staff.filter(r=>(r.name+' '+r.email).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())&&(filter==='all'||(filter==='sold'?sold(r)>0:filter==='no_activity'?r.activities===0:r.total>0))).sort((a,b)=>metricValue(b,metric)-metricValue(a,metric)||a.name.localeCompare(b.name)||a.email.localeCompare(b.email));
 const currentPage=Math.min(page,Math.max(1,Math.ceil(shown.length/8))),visible=shown.slice((currentPage-1)*8,currentPage*8),person=staff.find(r=>r.email===selected);
 const totals=staff.reduce((a,r)=>({total:a.total+r.total,won:a.won+(r.counts.won||0),direct:a.direct+(r.direct_sales||0),activities:a.activities+r.activities}),{total:0,won:0,direct:0,activities:0});
 const max=Math.max(1,...shown.map(r=>metricValue(r,metric))),meta=metrics.find(m=>m.value===metric)!;
 const setQuick=(v:string)=>{setFilter(v);setPage(1);};
 const identity=(r:MemberPerformance)=><Button type="link" className="performance-person-link" onClick={()=>setSelected(r.email)}><strong>{r.name}</strong><small>{r.email}</small></Button>;
 const rate=(r:MemberPerformance)=>r.total?<div className="performance-rate"><strong>{conversion(r).toFixed(1)}%</strong><Progress aria-label={`${r.name} хөрвөлт ${conversion(r).toFixed(1)} хувь`} percent={conversion(r)} showInfo={false} strokeColor="#8f3a05"/><small>{count(r.counts.won||0)} / {count(r.total)} хүсэлт</small></div>:<span className="muted">Хүсэлтгүй</span>;
 const columns:ColumnsType<MemberPerformance>=[{title:'Ажилтан',key:'name',width:260,render:(_,r)=>identity(r)},{title:'Хүсэлт',dataIndex:'total',align:'right',render:n=>count(n)},{title:'Худалдан авалт',key:'sold',align:'right',render:(_,r)=><><strong>{count(sold(r))}</strong><small>Хүсэлт {count(r.counts.won||0)} · Шууд {count(r.direct_sales||0)}</small></>},{title:'Үйлдэл',dataIndex:'activities',align:'right',render:n=>count(n)},...(metric==='amount'?[{title:'Шууд орлого',key:'amount',align:'right' as const,render:(_:unknown,r:MemberPerformance)=>count(r.direct_amount||0)+' ₮'}]:[]),{title:'Хөрвөлт',key:'conversion',width:165,render:(_,r)=>rate(r)},{title:'Дэлгэрэнгүй',key:'detail',width:115,render:(_,r)=><Button aria-label={r.name+' үзүүлэлт нээх'} onClick={()=>setSelected(r.email)}>Нээх</Button>}];
 return <section className="panel team-report team-performance" aria-label="Ажилтны үзүүлэлт">
 <div className="performance-heading"><div><div className="eyebrow">БОРЛУУЛАЛТЫН БАГ</div><h2>Ажилтан тус бүрийн үзүүлэлт</h2><p className="muted">{from||'Эхнээс'} — {to||'Өнөөдөр'} · Улаанбаатарын цаг</p></div><Tag>{staff.length} ажилтан</Tag></div>
 <div className="performance-summary"><Card size="small"><Statistic title="Хариуцаж буй хүсэлт" value={totals.total}/><small>Сонгосон хугацаанд үүссэн</small></Card><Card size="small"><Statistic title="Нийт худалдан авалт" value={totals.won+totals.direct}/><small>Хүсэлт {count(totals.won)} + шууд {count(totals.direct)}</small></Card><Card size="small"><Statistic title="Бүртгэсэн үйлдэл" value={totals.activities}/><small>Сонгосон хугацаанд хийсэн</small></Card><Card size="small"><Statistic title="Багийн хөрвөлт" value={totals.total?totals.won/totals.total*100:'—'} precision={1} suffix={totals.total?'%':undefined}/><small>Худалдан авсан хүсэлт / нийт хүсэлт</small></Card></div>
 {!!unassigned?.total&&<Alert type="info" showIcon title={`Хуваарилаагүй ${count(unassigned.total)} хүсэлт`} description="Ажилтнуудын үзүүлэлт болон дээрх нийлбэрт оруулаагүй. Ерөнхий хүсэлтийн тайланд багтана."/>}
 <details className="performance-method"><summary>Үзүүлэлтүүдийг хэрхэн тооцсон бэ?</summary><p>Хүсэлтийг үүссэн огноо, одоогийн хариуцагч болон одоогийн төлөвөөр тооцно. Үйлдэл нь сонгосон хугацаанд бүртгэсэн бүх үйлдэл; зөвхөн дуудлагын тоо биш.</p><p>Шууд борлуулалтыг борлуулсан огноогоор тооцно. Нийт худалдан авалт нь бүртгэлийн тоо, барааны ширхэг биш. Шууд борлуулалт хүсэлтийн хөрвөлтөд орохгүй. Хөрвөлтийн хувийг хүсэлтийн тоотой нь хамт харьцуулна.</p></details>
 <div className="performance-controls"><Input.Search aria-label="Үзүүлэлтээс ажилтан хайх" placeholder="Нэр, и-мэйлээр хайх" allowClear value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><Select<Metric> aria-label="Үзүүлэлт эрэмбэлэх" value={metric} options={metrics} onChange={v=>{setMetric(v);setPage(1);}}/><Segmented aria-label="Үзүүлэлтийн харагдац" value={view} options={[{value:'list',label:'Жагсаалт'},{value:'chart',label:'График'}]} onChange={setView}/></div>
 <Space wrap className="performance-quick">{[{value:'all',label:'Бүх ажилтан'},{value:'sold',label:'Худалдан авалттай'},{value:'requests',label:'Хүсэлттэй'},{value:'no_activity',label:'Үйлдэл бүртгээгүй'}].map(f=><Button key={f.value} type={filter===f.value?'primary':'default'} aria-pressed={filter===f.value} onClick={()=>setQuick(f.value)}>{f.label}</Button>)}{(query||filter!=='all')&&<Button onClick={()=>{setQuery('');setQuick('all');}}>Шүүлт цэвэрлэх</Button>}</Space>
 <p className="muted" role="status">{shown.length} / {staff.length} ажилтан · {meta.label} ихээс бага руу. Дээрх нийлбэр бүх ажилтных.</p>
 {!shown.length?<Empty description="Сонголтод тохирох ажилтан алга"/>:view==='chart'?<div className="performance-chart" aria-label={meta.label+' харьцуулалт'}>{visible.map(r=><button className="performance-bar" key={r.email} onClick={()=>setSelected(r.email)} aria-label={r.name+' үзүүлэлт нээх'}><span><strong>{r.name}</strong><b>{metric==='conversion'?(r.total?conversion(r).toFixed(1)+'%':'Хүсэлтгүй'):count(metricValue(r,metric))+' '+meta.unit}</b></span><Progress aria-label={r.name+' '+meta.label} percent={metricValue(r,metric)/max*100} showInfo={false} strokeColor="#8f3a05"/><small>{count(r.total)} хүсэлт · {count(sold(r))} худалдан авалт</small></button>)}<small className="muted">Зураасны урт нь шүүлтэд тохирох бүх ажилтны хамгийн их дүнтэй харьцуулсан хэмжээ.</small></div>:mobile?<div className="performance-mobile">{visible.map(r=><Card key={r.email} size="small">{identity(r)}<Descriptions column={1} size="small" items={[{key:'total',label:'Хүсэлт',children:count(r.total)},{key:'sold',label:'Худалдан авалт',children:`${sold(r)} · Хүсэлт ${r.counts.won||0} + шууд ${r.direct_sales||0}`},{key:'actions',label:'Бүртгэсэн үйлдэл',children:count(r.activities)},...(metric==='amount'?[{key:'amount',label:'Шууд орлого',children:count(r.direct_amount||0)+' ₮'}]:[]),{key:'rate',label:'Хөрвөлт',children:rate(r)}]}/><Button block onClick={()=>setSelected(r.email)}>Дэлгэрэнгүй</Button></Card>)}</div>:<Table rowKey="email" columns={columns} dataSource={visible} pagination={false} size="middle" scroll={{x:850}}/>}
 <Pagination className="performance-pagination" current={currentPage} pageSize={8} total={shown.length} showSizeChanger={false} hideOnSinglePage onChange={setPage}/>
 <Drawer title={person?.name||'Ажилтны үзүүлэлт'} open={!!person} onClose={()=>setSelected(null)} size={mobile?'100%':540} className="performance-drawer"><p className="muted">{person?.email}<br/>{from||'Эхнээс'} — {to||'Өнөөдөр'} · УБ</p>{person&&<><Descriptions bordered size="small" column={1} items={[{key:'total',label:'Хариуцаж буй хүсэлт',children:count(person.total)},{key:'won',label:'Хүсэлтээс худалдан авсан',children:count(person.counts.won||0)},{key:'direct',label:'Шууд худалдан авалт',children:count(person.direct_sales||0)},{key:'sold',label:'Нийт худалдан авалт',children:count(sold(person))},{key:'amount',label:'Шууд борлуулалтын орлого',children:count(person.direct_amount||0)+' ₮'},{key:'actions',label:'Бүртгэсэн үйлдэл',children:count(person.activities)},{key:'rate',label:'Хүсэлтийн хөрвөлт',children:rate(person)}]}/><h3>Хүсэлтийн одоогийн төлөв</h3><div className="performance-statuses">{Object.entries(stages).map(([key,label])=><div key={key}><span>{label}<strong>{count(person.counts[key]||0)}</strong></span><Progress aria-label={label+' '+(person.counts[key]||0)+' хүсэлт'} percent={person.total?(person.counts[key]||0)/person.total*100:0} showInfo={false} strokeColor={key==='won'?'#236315':'#697b96'}/></div>)}</div><p className="muted">Шууд борлуулалтын орлого нь зээлийн хүсэлтийн борлуулалтын дүнг агуулахгүй.</p></>}</Drawer>
 </section>;
}
