import {assignmentNotice} from './notifications';
import {env} from 'cloudflare:workers';import {z} from 'zod';
import {defaults,label,configSchema,transformRows,type SheetConfig} from './sheet-model';import {closed,type Lead} from './crm';
const db=()=>env.DB!;const enc=new TextEncoder();
const base64=(v:Uint8Array)=>btoa(String.fromCharCode(...v));const bytes=(v:string)=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));const url64=(v:Uint8Array)=>base64(v).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
const keySchema=z.object({type:z.literal('service_account'),client_email:z.string().email().regex(/\.iam\.gserviceaccount\.com$/),private_key:z.string().min(100).max(12000)});
type Credential=z.infer<typeof keySchema>;
async function cipherKey(){const v=env.CRM_CONNECTION_ENCRYPTION_KEY;if(!v)throw new Error('Холболтын хамгаалалтын тохиргоо бэлэн биш.');return crypto.subtle.importKey('raw',bytes(v),{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function seal(k:Credential){const iv=crypto.getRandomValues(new Uint8Array(12));const v=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('antmall-google-sheets-v1')},await cipherKey(),enc.encode(JSON.stringify(k)));return base64(iv)+'.'+base64(new Uint8Array(v));}
async function unseal(v:string){const [i,c]=v.split('.');const s=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(i),additionalData:enc.encode('antmall-google-sheets-v1')},await cipherKey(),bytes(c));return keySchema.parse(JSON.parse(new TextDecoder().decode(s)));}
async function token(k:Credential){const iat=Math.floor(Date.now()/1000);const h=url64(enc.encode(JSON.stringify({alg:'RS256',typ:'JWT'}))),p=url64(enc.encode(JSON.stringify({iss:k.client_email,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:'https://oauth2.googleapis.com/token',iat,exp:iat+3600})));const pem=k.private_key.replace(/-----[^-]+-----/g,'').replace(/\s/g,'');const key=await crypto.subtle.importKey('pkcs8',bytes(pem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(h+'.'+p));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:h+'.'+p+'.'+url64(new Uint8Array(signature))}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('Google холболтын түлхүүр хүчингүй эсвэл эрх хүрэлцэхгүй.');const d=await r.json() as {access_token?:string};if(!d.access_token)throw new Error('Google нэвтрэлт амжилтгүй.');return d.access_token;}
type Connection={config:string;credential:string|null;email:string|null;enabled:number;checked:number;last_at:string|null;last_error:string|null;last_result:string|null;lease:string|null;lease_until:number};
export async function connection(){return await db().prepare('SELECT * FROM sheet_connection WHERE id=1').first<Connection>();}
export async function publicConnection(){const c=await connection();return {config:c?configSchema.parse(JSON.parse(c.config)):defaults,email:c?.email||null,hasCredential:!!c?.credential,enabled:!!c?.enabled,checked:!!c?.checked,lastAt:c?.last_at||null,lastError:c?.last_error||null,lastResult:c?.last_result?JSON.parse(c.last_result):null};}
export async function saveConnection(raw:unknown,credential?:unknown){const config=configSchema.parse(raw);if(new Set(Object.values(config.columns)).size!==6)throw new Error('Баганууд давхцахгүй байна.');const names=Object.keys(config.aliases).map(label);if(new Set(names).size!==names.length)throw new Error('Ажилтны нэр давхардсан байна.');const stageNames=Object.keys(config.statusMap).map(label);if(new Set(stageNames).size!==stageNames.length)throw new Error('Төлөвийн нэр давхардсан байна.');for(const email of Object.values(config.aliases)){if(!await db().prepare('SELECT email FROM members WHERE lower(email)=? AND active=1').bind(email.toLowerCase()).first())throw new Error('Идэвхтэй CRM ажилтантай нэрийг холбоно уу.');}
 const old=await connection();if(old&&old.lease_until>Date.now())throw new Error('Синк дууссаны дараа тохиргоог шинэчилнэ үү.');if(old){const prev=JSON.parse(old.config);if((prev.spreadsheetId!==config.spreadsheetId||prev.tab!==config.tab)&&await db().prepare('SELECT 1 FROM sheet_links LIMIT 1').first())throw new Error('Өгөгдөлтэй эх хүснэгтийг солихгүй. Шилжүүлэлтийг тусад нь хийнэ.');}
 const cred=credential?keySchema.parse(credential):null;const sealed=cred?await seal(cred):old?.credential||null;
 await db().prepare('INSERT INTO sheet_connection(id,config,credential,email,enabled,checked) VALUES(1,?,?,?,0,0) ON CONFLICT(id) DO UPDATE SET config=excluded.config,credential=excluded.credential,email=excluded.email,enabled=0,checked=0,last_error=NULL').bind(JSON.stringify(config),sealed,cred?.client_email||old?.email||null).run();return publicConnection();}
async function readGoogle(c:Connection){if(!c.credential)throw new Error('Google-ийн унших эрхийн түлхүүрийг холбоно уу.');const config=configSchema.parse(JSON.parse(c.config));const auth=await token(await unseal(c.credential));const root='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(config.spreadsheetId);
 const read=async(url:string)=>{const r=await fetch(url,{headers:{Authorization:'Bearer '+auth},signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(r.status===403?'Google Sheets API болон хүснэгтийн Viewer эрхийг шалгана уу.':r.status===404?'Google Sheet эсвэл таб олдсонгүй.':r.status===429?'Google-ийн түр хязгаар үйлчилж байна. Дараа дахин оролдоно.':'Google хүснэгтийг уншиж чадсангүй.');return r.json();};
 const meta=await read(root+'?fields=sheets(properties(title,gridProperties(rowCount,columnCount)))') as {sheets:{properties:{title:string;gridProperties:{rowCount:number;columnCount:number}}}[]};const tab=meta.sheets.find(s=>s.properties.title===config.tab);if(!tab)throw new Error('Табын нэр олдсонгүй.');if(tab.properties.gridProperties.rowCount>60000)throw new Error('60,000-аас их мөртэй хүснэгтэд тусдаа импортын хүрээ тохируулна.');
 const params=new URLSearchParams({valueRenderOption:'UNFORMATTED_VALUE',dateTimeRenderOption:'SERIAL_NUMBER'});for(const col of [config.columns.timestamp,config.columns.phone,config.columns.product,config.columns.owner,config.columns.status,config.columns.registration])params.append('ranges',"'"+config.tab.replaceAll("'","''")+"'!"+col+'1:'+col+tab.properties.gridProperties.rowCount);
 const response=await read(root+'/values:batchGet?'+params) as {valueRanges:{values:unknown[][]}[]};if(response.valueRanges.length!==6)throw new Error('Google-ийн баганын хариу бүрэн биш.');const columns=response.valueRanges.map(r=>r.values||[]);[config.headers.timestamp,config.headers.phone,config.headers.product,config.headers.owner,config.headers.status,config.headers.registration].forEach((name,i)=>{if(label(columns[i][0]?.[0])!==label(name))throw new Error('Баганын гарчиг өөрчлөгдсөн: '+name);});return {config,...transformRows(columns,config)};}
export async function testConnection(){const c=await connection();if(!c)throw new Error('Холболтын тохиргоог хадгална уу.');const result=await readGoogle(c);const owners=[...new Set(result.rows.map(r=>r.owner))].filter(Boolean);const unmapped=owners.filter(o=>!Object.entries(result.config.aliases).some(([k])=>label(k)===label(o)));const preview={counts:result.counts,eligible:result.rows.length,owners,unmapped,issues:result.issues.slice(0,50),issueCount:result.issues.length};await db().prepare('UPDATE sheet_connection SET checked=1,last_error=NULL,last_result=? WHERE id=1').bind(JSON.stringify(preview)).run();return preview;}
export async function setEnabled(enabled:boolean){const c=await connection();if(!c?.credential||!c.checked)throw new Error('Эхлээд холболтыг шалгана уу.');await db().prepare('UPDATE sheet_connection SET enabled=? WHERE id=1').bind(enabled?1:0).run();}
// Deployment-provided credential is consumed only when no connection key exists.
// Normal validation runs before enabling; existing user settings and stop controls win.
export async function bootstrapGoogleConnection(){
 const raw=env.CRM_GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)return false;
 const old=await connection();if(old?.credential)return false;
 const credential=keySchema.parse(JSON.parse(raw));const sealed=await seal(credential);
 const result=await db().prepare('INSERT INTO sheet_connection(id,config,credential,email,enabled,checked) VALUES(1,?,?,?,0,0) ON CONFLICT(id) DO UPDATE SET credential=excluded.credential,email=excluded.email,enabled=0,checked=0 WHERE sheet_connection.credential IS NULL').bind(JSON.stringify(defaults),sealed,credential.client_email).run();
 if(!result.meta.changes)return false;
 try{await testConnection();await setEnabled(true);return true;}
 catch(e){await db().prepare('UPDATE sheet_connection SET last_error=? WHERE id=1').bind((e as Error).message.slice(0,250)).run();throw e;}
}
export async function syncSheets(){const c=await connection();if(!c?.enabled)return {state:'not_connected'};const lease=crypto.randomUUID(),now=Date.now();const locked=await db().prepare('UPDATE sheet_connection SET lease=?,lease_until=? WHERE id=1 AND enabled=1 AND lease_until<? AND (last_at IS NULL OR last_at<?)').bind(lease,now+120000,now,new Date(now-25000).toISOString()).run();if(!locked.meta.changes)return{state:'waiting'};
 try{const read=await readGoogle(c);const stats={...await applyRows(read.rows,read.issues,lease),counts:read.counts};await db().prepare('UPDATE sheet_connection SET last_at=?,last_error=NULL,last_result=?,lease_until=0,lease=NULL WHERE id=1 AND lease=?').bind(new Date().toISOString(),JSON.stringify(stats),lease).run();return{state:'synced',...stats};}catch(e){await db().prepare('UPDATE sheet_connection SET last_at=?,last_error=?,lease=NULL,lease_until=0 WHERE id=1 AND lease=?').bind(new Date().toISOString(),(e as Error).message.slice(0,250),lease).run();throw e;}}
export async function applyRows(rows:ReturnType<typeof transformRows>['rows'],issues:ReturnType<typeof transformRows>['issues'],lease:string){
 const links=await db().prepare('SELECT * FROM sheet_links').all<{external_key:string;lead_id:string;owner_label:string;owner_email:string}>();const byKey=new Map(links.results.map(l=>[l.external_key,l]));const members=await db().prepare('SELECT email FROM members WHERE active=1').all<{email:string}>();const active=new Set(members.results.map(m=>m.email));const existingRows=await db().prepare('SELECT id,phone,registration,registration_manual FROM leads').all<{id:string;phone:string;registration:string;registration_manual:number}>();const existing=new Map(existingRows.results.map(l=>[l.id,l]));const now=new Date().toISOString();let added=0,reassigned=0,backfilled=0,unchanged=0,waiting=0,handled=0,pending=0;const unresolved=new Set<string>();
 const stoppedRows=await db().prepare('SELECT phone FROM suppressions').all<{phone:string}>();const stopped=new Set(stoppedRows.results.map(r=>r.phone));let suppressed=0;
 const jobs=await Promise.all(rows.map(async r=>{const digest=await crypto.subtle.digest('SHA-256',enc.encode(r.identity));return {...r,key:url64(new Uint8Array(digest))};}));
 jobs.sort((a,b)=>Number(byKey.has(b.key))-Number(byKey.has(a.key))||b.created.localeCompare(a.created));
 for(const r of jobs){if(stopped.has(r.phone)){suppressed++;continue;}const owner=active.has(r.ownerEmail)?r.ownerEmail:'__sheet_unassigned__';if(owner==='__sheet_unassigned__')unresolved.add(r.owner||'(Хуваарилаагүй)');const link=byKey.get(r.key);const oldLead=link?existing.get(link.lead_id):null;const fillRegistration=!!(link&&r.registration&&!oldLead?.registration&&!oldLead?.registration_manual);if(link&&link.owner_email===owner&&link.owner_label===r.owner&&!fillRegistration){unchanged++;continue;}if(handled>=80){pending++;continue;}handled++;
 if(link){const lead=await db().prepare('SELECT * FROM leads WHERE id=?').bind(link.lead_id).first<Lead>();if(!lead){issues.push({row:r.row,reason:'CRM холбоосын хүсэлт олдсонгүй'});continue;}const op=crypto.randomUUID();const result=await db().batch([
 db().prepare(`UPDATE leads SET registration=CASE WHEN registration='' AND registration_manual=0 THEN ? ELSE registration END,owner=?,next_at=CASE WHEN next_action='Ажилтантай холбох хүлээлт' AND ?!='__sheet_unassigned__' AND status NOT IN ('won','lost','invalid') AND NOT EXISTS(SELECT 1 FROM suppressions WHERE phone=leads.phone) THEN ? ELSE next_at END,next_action=CASE WHEN next_action='Ажилтантай холбох хүлээлт' AND ?!='__sheet_unassigned__' THEN 'Sheet хүсэлт хянах' ELSE next_action END,version=version+1,updated_at=?,op=? WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM sheet_connection WHERE id=1 AND enabled=1 AND lease=? AND lease_until>?)`).bind(r.registration,owner,owner,now,owner,now,op,lead.id,lead.version,lease,Date.now()),
 db().prepare("INSERT INTO activities(id,lead_id,phone,kind,note,actor,created_at) SELECT ?,id,phone,'sheet_update',?,'Google Sheets',? FROM leads WHERE id=? AND op=?").bind(op,(link.owner_email===owner&&link.owner_label===r.owner?'Sheet-ээс регистрийн дугаарыг нөхөв':'Sheet хуваарилалт: '+(r.owner||'хоосон')+' → '+(owner==='__sheet_unassigned__'?'Холбох ажилтан хүлээж байна':owner)),now,lead.id,op),
 db().prepare('UPDATE sheet_links SET row_number=?,owner_label=?,owner_email=?,updated_at=? WHERE external_key=? AND EXISTS(SELECT 1 FROM leads WHERE id=? AND op=?)').bind(r.row,r.owner,owner,now,r.key,lead.id,op),assignmentNotice(lead.id,op,now,lead.owner)]);if(result[0].meta.changes){if(fillRegistration)backfilled++;if(link.owner_email!==owner||link.owner_label!==r.owner)reassigned++;}else pending++;
 }else{
 const id='sheet-'+r.key,op=crypto.randomUUID();const paused=owner==='__sheet_unassigned__'||r.status==='review'||closed.includes(r.status);const res=await db().batch([
 db().prepare('INSERT INTO leads(id,name,phone,product,source,owner,status,next_at,next_action,created_at,updated_at,op,registration) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM sheet_links WHERE external_key=?) AND NOT EXISTS(SELECT 1 FROM leads WHERE id=?) AND NOT EXISTS(SELECT 1 FROM suppressions WHERE phone=?) AND EXISTS(SELECT 1 FROM sheet_connection WHERE id=1 AND enabled=1 AND lease=? AND lease_until>?)').bind(id,'Зээлийн хүсэлт · '+r.phone.slice(-4),r.phone,r.product,'Google Sheets',owner,r.status,paused?null:now,closed.includes(r.status)?'Хаагдсан':r.status==='review'?'Мэдээлэл шалгах':owner==='__sheet_unassigned__'?'Ажилтантай холбох хүлээлт':'Sheet хүсэлт хянах',r.created,now,op,r.registration,r.key,id,r.phone,lease,Date.now()),
 db().prepare('INSERT INTO sheet_links(external_key,lead_id,row_number,owner_label,owner_email,updated_at) SELECT ?,id,?,?,?,? FROM leads WHERE id=? AND op=?').bind(r.key,r.row,r.owner,owner,now,id,op),
 db().prepare("INSERT INTO activities(id,lead_id,phone,kind,note,actor,created_at) SELECT ?,id,phone,'sheet_import',?,'Google Sheets',? FROM leads WHERE id=? AND op=?").bind(op,'Google Sheet-ийн '+r.row+'-р мөрөөс импортлов. Хариуцагч: '+(r.owner||'хоосон'),now,id,op),assignmentNotice(id,op,now)]);if(res[0].meta.changes){added++;if(paused&&!closed.includes(r.status))waiting++;}else pending++;
 }}return{added,reassigned,backfilled,suppressed,unchanged,waiting,pending,unmapped:[...unresolved],issues:issues.slice(0,50),issueCount:issues.length,eligible:rows.length};}
