import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const organization = sqliteTable('organization', { id: integer('id').primaryKey(), owner: text('owner').notNull() });
export const members = sqliteTable('members', { email: text('email').primaryKey(), userId: text('user_id'), name: text('name').notNull(), role: text('role').notNull(), active: integer('active').notNull().default(1), lastSeen: text('last_seen') });
export const leads = sqliteTable('leads', {
 id:text('id').primaryKey(), name:text('name').notNull(), phone:text('phone').notNull(), registration:text('registration').notNull().default(''), registrationManual:integer('registration_manual').notNull().default(0), product:text('product').notNull(), source:text('source').notNull(), owner:text('owner').notNull(), status:text('status').notNull(), nextAt:text('next_at'), nextAction:text('next_action').notNull(), recycleAt:text('recycle_at'), connected:integer('connected').notNull().default(0), createdAt:text('created_at').notNull(), updatedAt:text('updated_at').notNull(), version:integer('version').notNull().default(1), op:text('op').notNull(),
}, t=>[index('leads_owner_due').on(t.owner,t.nextAt),index('leads_phone').on(t.phone),index('leads_created').on(t.createdAt),index('leads_status').on(t.status),index('leads_owner_created').on(t.owner,t.createdAt)]);
export const activities=sqliteTable('activities',{id:text('id').primaryKey(),leadId:text('lead_id').notNull(),phone:text('phone').notNull(),kind:text('kind').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('activity_lead').on(t.leadId,t.createdAt),index('activity_attempts').on(t.phone,t.kind,t.createdAt),index('activity_actor').on(t.actor,t.createdAt)]);
export const suppressions=sqliteTable('suppressions',{phone:text('phone').primaryKey(),reason:text('reason').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()});
export const sheetConnection=sqliteTable('sheet_connection',{id:integer('id').primaryKey(),config:text('config').notNull(),credential:text('credential'),email:text('email'),enabled:integer('enabled').notNull().default(0),lastAt:text('last_at'),lastError:text('last_error'),lastResult:text('last_result'),lease:text('lease'),leaseUntil:integer('lease_until').notNull().default(0),checked:integer('checked').notNull().default(0)});
export const sheetLinks=sqliteTable('sheet_links',{externalKey:text('external_key').primaryKey(),leadId:text('lead_id').notNull(),rowNumber:integer('row_number').notNull(),ownerLabel:text('owner_label').notNull(),ownerEmail:text('owner_email').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('sheet_link_lead').on(t.leadId)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),recipient:text('recipient').notNull(),leadId:text('lead_id').notNull(),kind:text('kind').notNull(),createdAt:text('created_at').notNull(),readAt:text('read_at'),dueAt:text('due_at'),alertedAt:text('alerted_at')},t=>[index('notifications_recipient_time').on(t.recipient,t.createdAt),index('notifications_recipient_read').on(t.recipient,t.readAt)]);
// Ганц түлхүүр-утгын хүснэгт: цаашид админы тохиргоо нэмэхэд шинэ багана биш, зөвхөн шинэ key ашиглана.
export const appSettings=sqliteTable('app_settings',{key:text('key').primaryKey(),value:text('value').notNull(),updatedAt:text('updated_at').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),pairKey:text('pair_key').notNull(),sender:text('sender').notNull(),recipient:text('recipient').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull(),readAt:text('read_at')},t=>[index('messages_pair').on(t.pairKey,t.createdAt),index('messages_recipient_read').on(t.recipient,t.readAt)]);
// Бүх идэвхтэй ажилтанд нээлттэй нэг дундын суваг; уншсан эсэхийг мессеж бүрээр биш, хүн тус бүрийн сүүлд уншсан цагаар хэмжинэ.
export const teamMessages=sqliteTable('team_messages',{id:text('id').primaryKey(),sender:text('sender').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('team_messages_created').on(t.createdAt)]);
export const teamReads=sqliteTable('team_reads',{email:text('email').primaryKey(),lastReadAt:text('last_read_at').notNull()});
