import { sqliteTable, text, integer, real, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const directSaleRequests=sqliteTable('direct_sale_requests',{id:text('id').primaryKey(),requester:text('requester').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),saleId:text('sale_id'),reviewedBy:text('reviewed_by'),reviewedAt:text('reviewed_at'),reviewNote:text('review_note').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('direct_sale_requests_status').on(t.status,t.createdAt),index('direct_sale_requests_requester').on(t.requester,t.createdAt)]);
export const inventoryProductCodes=sqliteTable('inventory_product_codes',{id:integer('id').primaryKey({autoIncrement:true}),productKey:text('product_key').notNull()},t=>[uniqueIndex('inventory_product_codes_key').on(t.productKey)]);
export const siteCatalog=sqliteTable('site_catalog',{id:text('id').primaryKey(),code:text('code').notNull(),name:text('name').notNull(),capacity:text('capacity').notNull(),color:text('color').notNull(),variant:text('variant').notNull(),importedAt:text('imported_at').notNull()});
export const siteStockLinks=sqliteTable('site_stock_links',{productKey:text('product_key').primaryKey(),siteId:text('site_id').notNull(),siteCode:text('site_code').notNull(),enabled:integer('enabled').notNull().default(0),confirmedBy:text('confirmed_by').notNull(),confirmedAt:text('confirmed_at').notNull(),lastQty:integer('last_qty'),lastSyncedAt:text('last_synced_at'),lastAttemptAt:text('last_attempt_at'),lastError:text('last_error').notNull().default('')},t=>[uniqueIndex('site_stock_links_site').on(t.siteId)]);
export const siteStockControl=sqliteTable('site_stock_control',{id:integer('id').primaryKey(),automatic:integer('automatic').notNull().default(0),lockToken:text('lock_token'),lockUntil:text('lock_until')});
export const siteStockEvents=sqliteTable('site_stock_events',{id:text('id').primaryKey(),productKey:text('product_key').notNull(),siteId:text('site_id').notNull(),qty:integer('qty'),action:text('action').notNull(),actor:text('actor').notNull(),message:text('message').notNull(),createdAt:text('created_at').notNull()});
export const organization = sqliteTable('organization', { id: integer('id').primaryKey(), owner: text('owner').notNull() });
export const members = sqliteTable('members', { email: text('email').primaryKey(), userId: text('user_id'), name: text('name').notNull(), role: text('role').notNull(), active: integer('active').notNull().default(1), lastSeen: text('last_seen'), phone: text('phone'), avatar: text('avatar') });
export const leads = sqliteTable('leads', {
 id:text('id').primaryKey(), name:text('name').notNull(), phone:text('phone').notNull(), registration:text('registration').notNull().default(''), registrationManual:integer('registration_manual').notNull().default(0), product:text('product').notNull(), source:text('source').notNull(), owner:text('owner').notNull(), status:text('status').notNull(), nextAt:text('next_at'), nextAction:text('next_action').notNull(), recycleAt:text('recycle_at'), connected:integer('connected').notNull().default(0), createdAt:text('created_at').notNull(), updatedAt:text('updated_at').notNull(), version:integer('version').notNull().default(1), op:text('op').notNull(), deletedAt:text('deleted_at'),
}, t=>[index('leads_owner_due').on(t.owner,t.nextAt),index('leads_phone').on(t.phone),index('leads_created').on(t.createdAt),index('leads_status').on(t.status),index('leads_owner_created').on(t.owner,t.createdAt)]);
export const activities=sqliteTable('activities',{id:text('id').primaryKey(),leadId:text('lead_id').notNull(),phone:text('phone').notNull(),kind:text('kind').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('activity_lead').on(t.leadId,t.createdAt),index('activity_attempts').on(t.phone,t.kind,t.createdAt),index('activity_actor').on(t.actor,t.createdAt)]);
export const suppressions=sqliteTable('suppressions',{phone:text('phone').primaryKey(),reason:text('reason').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()});
export const sheetConnection=sqliteTable('sheet_connection',{id:integer('id').primaryKey(),config:text('config').notNull(),credential:text('credential'),email:text('email'),enabled:integer('enabled').notNull().default(0),lastAt:text('last_at'),lastError:text('last_error'),lastResult:text('last_result'),lease:text('lease'),leaseUntil:integer('lease_until').notNull().default(0),checked:integer('checked').notNull().default(0)});
export const sheetLinks=sqliteTable('sheet_links',{externalKey:text('external_key').primaryKey(),leadId:text('lead_id').notNull(),rowNumber:integer('row_number').notNull(),ownerLabel:text('owner_label').notNull(),ownerEmail:text('owner_email').notNull(),autoAssigned:integer('auto_assigned').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[index('sheet_link_lead').on(t.leadId)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),recipient:text('recipient').notNull(),leadId:text('lead_id').notNull(),kind:text('kind').notNull(),createdAt:text('created_at').notNull(),readAt:text('read_at'),dueAt:text('due_at'),alertedAt:text('alerted_at')},t=>[index('notifications_recipient_time').on(t.recipient,t.createdAt),index('notifications_recipient_read').on(t.recipient,t.readAt)]);
// Ганц түлхүүр-утгын хүснэгт: цаашид админы тохиргоо нэмэхэд шинэ багана биш, зөвхөн шинэ key ашиглана.
export const appSettings=sqliteTable('app_settings',{key:text('key').primaryKey(),value:text('value').notNull(),updatedAt:text('updated_at').notNull()});
// Лидийн төлөв тус бүрт (won, lost г.м) тохируулж болох автомат SMS дүрэм; статус тус бүрт нэг л дүрэм байна.
export const smsRules=sqliteTable('sms_rules',{id:text('id').primaryKey(),status:text('status').notNull(),message:text('message').notNull(),enabled:integer('enabled').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('sms_rules_status').on(t.status)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),pairKey:text('pair_key').notNull(),sender:text('sender').notNull(),recipient:text('recipient').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull(),readAt:text('read_at'),replyToId:text('reply_to_id'),replyToSender:text('reply_to_sender'),replyToBody:text('reply_to_body'),image:text('image')},t=>[index('messages_pair').on(t.pairKey,t.createdAt),index('messages_recipient_read').on(t.recipient,t.readAt)]);
// Одоо "all" (бүх ажилчид), "marketing", "sales" гэсэн хэд хэдэн суваг байдаг тул channel-аар ялгана;
// уншсан эсэхийг мессеж бүрээр биш, хүн + суваг хосын сүүлд уншсан цагаар хэмжинэ.
// mentions нь @дурдсан гишүүдийн имэйлийн JSON массив (жишээ нь ["a@x.test"]); mentionsAll нь @Бүгд/@all
// дурдсан эсэх, тухайн сувгийн бүх гишүүнд "дурдагдсан" тэмдэглэгээ өгнө.
export const teamMessages=sqliteTable('team_messages',{id:text('id').primaryKey(),channel:text('channel').notNull().default('all'),sender:text('sender').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull(),replyToId:text('reply_to_id'),replyToSender:text('reply_to_sender'),replyToBody:text('reply_to_body'),image:text('image'),mentions:text('mentions'),mentionsAll:integer('mentions_all').notNull().default(0)},t=>[index('team_messages_created').on(t.channel,t.createdAt)]);
export const teamReads=sqliteTable('team_reads',{email:text('email').notNull(),channel:text('channel').notNull().default('all'),lastReadAt:text('last_read_at').notNull()},t=>[uniqueIndex('team_reads_email_channel').on(t.email,t.channel)]);
// Ахлах, Админ (админтай адил эрхтэй Удирдлага орно) чөлөөтэй үүсгэдэг групп чат; team_messages/team_reads-ийг
// "all"/"marketing"/"sales"-тай адилаар channel id-гаараа дундаа ашиглана, схем өөрчлөх шаардлагагүй.
export const groupChats=sqliteTable('group_chats',{id:text('id').primaryKey(),name:text('name').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()});
export const groupChatMembers=sqliteTable('group_chat_members',{channelId:text('channel_id').notNull(),email:text('email').notNull()},t=>[uniqueIndex('group_chat_members_unique').on(t.channelId,t.email),index('group_chat_members_email').on(t.email)]);
// DM болон багийн мессеж хоёуланд нь ашиглагддаг тул message_kind-ээр ялгана; нэг хүн нэг мессежид
// ижил emoji-г давхар нэмэхгүй байхыг unique index-ээр (toggle: дахин дарвал хасна) хангана.
export const messageReactions=sqliteTable('message_reactions',{id:text('id').primaryKey(),messageKind:text('message_kind').notNull(),messageId:text('message_id').notNull(),emoji:text('emoji').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('reactions_message').on(t.messageKind,t.messageId),uniqueIndex('reactions_unique').on(t.messageKind,t.messageId,t.emoji,t.actor)]);
export const marketingTasks=sqliteTable('marketing_tasks',{id:text('id').primaryKey(),title:text('title').notNull(),channel:text('channel').notNull(),budget:integer('budget').notNull().default(0),owner:text('owner').notNull(),status:text('status').notNull(),dueAt:text('due_at'),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1),approvedAt:text('approved_at'),approvedBy:text('approved_by')},t=>[index('marketing_tasks_owner').on(t.owner,t.dueAt),index('marketing_tasks_status').on(t.status),index('marketing_tasks_created').on(t.createdAt)]);
export const marketingActivities=sqliteTable('marketing_activities',{id:text('id').primaryKey(),taskId:text('task_id').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('marketing_activity_task').on(t.taskId,t.createdAt)]);
export const itTasks=sqliteTable('it_tasks',{id:text('id').primaryKey(),title:text('title').notNull(),systemArea:text('system_area').notNull(),owner:text('owner').notNull(),status:text('status').notNull(),dueAt:text('due_at'),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('it_tasks_owner').on(t.owner,t.dueAt),index('it_tasks_status').on(t.status),index('it_tasks_created').on(t.createdAt)]);
export const itActivities=sqliteTable('it_activities',{id:text('id').primaryKey(),taskId:text('task_id').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('it_activity_task').on(t.taskId,t.createdAt)]);
// Санхүүгийн тооллого: бэлэн мөнгө, бараа, баримт г.м физик зүйлийг товлож тоолох ажил; хуучин
// category/expected_amount/actual_amount багана хэвээр үлдсэн ч ашиглагдахгүй, доорх бараа тус
// бүрийн мөр (inventory_count_lines) нь агуулах доторх бодит SKU-ийн тоог хардаг болсон.
export const inventoryCounts=sqliteTable('inventory_counts',{id:text('id').primaryKey(),title:text('title').notNull(),category:text('category').notNull(),owner:text('owner').notNull(),status:text('status').notNull(),dueAt:text('due_at'),expectedAmount:integer('expected_amount').notNull().default(0),actualAmount:integer('actual_amount'),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1),warehouseId:text('warehouse_id'),stockRevision:integer('stock_revision').notNull().default(-1)},t=>[index('inventory_counts_owner').on(t.owner,t.dueAt),index('inventory_counts_status').on(t.status),index('inventory_counts_created').on(t.createdAt)]);
export const inventoryCountActivities=sqliteTable('inventory_count_activities',{id:text('id').primaryKey(),countId:text('count_id').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('inventory_count_activity_count').on(t.countId,t.createdAt)]);
// Бараа материалын бүрэн бүртгэл: SKU (inventory_items), агуулах/салбар (inventory_warehouses), орлого
// (inventory_purchases), зарлага (inventory_sales) бүгд stock_moves-д +/- бичлэг үлдээж, одоогийн
// үлдэгдлийг SUM(qty_delta)-аар тооцоолно (тусдаа "одоогийн тоо" багана хөтлөхгүй тул зөрөхгүй).
export const inventoryWarehouses=sqliteTable('inventory_warehouses',{id:text('id').primaryKey(),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('inventory_warehouses_name').on(t.name)]);
export const inventoryItems=sqliteTable('inventory_items',{id:text('id').primaryKey(),imageUrl:text('image_url').notNull().default(''),productKey:text('product_key').notNull().default(''),barcode:text('barcode').notNull().default(''),code:text('code').notNull().default(''),brand:text('brand').notNull().default(''),category:text('category').notNull().default(''),name:text('name').notNull(),variant:text('variant').notNull().default(''),imei:text('imei'),capacity:text('capacity').notNull().default(''),color:text('color').notNull().default(''),supplier:text('supplier').notNull().default(''),minStock:integer('min_stock').notNull().default(0),salePrice:real('sale_price').notNull().default(0),cashPrice:real('cash_price'),active:integer('active').notNull().default(1),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('inventory_items_product').on(t.productKey),index('inventory_items_barcode').on(t.barcode),index('inventory_items_code').on(t.code),index('inventory_items_name').on(t.name)]);
export const inventoryStockMoves=sqliteTable('inventory_stock_moves',{id:text('id').primaryKey(),itemId:text('item_id').notNull(),warehouseId:text('warehouse_id').notNull(),kind:text('kind').notNull(),qtyDelta:integer('qty_delta').notNull(),unitCost:real('unit_cost'),valueCents:integer('value_cents').notNull().default(0),costEstimated:integer('cost_estimated').notNull().default(0),occurredAt:text('occurred_at'),refId:text('ref_id'),note:text('note').notNull().default(''),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('inventory_moves_item').on(t.itemId,t.warehouseId),index('inventory_moves_created').on(t.createdAt)]);
export const inventoryPurchases=sqliteTable('inventory_purchases',{id:text('id').primaryKey(),itemId:text('item_id').notNull(),warehouseId:text('warehouse_id').notNull(),qty:integer('qty').notNull(),orderNumber:text('order_number').notNull().default(''),status:text('status').notNull().default('received'),baseUnitCost:real('base_unit_cost').notNull().default(0),additionalCost:real('additional_cost').notNull().default(0),returnedQty:integer('returned_qty').notNull().default(0),unitCost:real('unit_cost').notNull().default(0),totalCost:real('total_cost').notNull().default(0),orderedAt:text('ordered_at'),receivedAt:text('received_at'),paymentStatus:text('payment_status').notNull().default(''),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('inventory_purchases_item').on(t.itemId),index('inventory_purchases_created').on(t.createdAt)]);
export const inventorySales=sqliteTable('inventory_sales',{id:text('id').primaryKey(),leadId:text('lead_id'),seller:text('seller').notNull().default(''),itemId:text('item_id').notNull(),warehouseId:text('warehouse_id').notNull(),qty:integer('qty').notNull(),billNumber:text('bill_number').notNull().default(''),account:text('account').notNull().default(''),commissionRate:real('commission_rate').notNull().default(0),commissionCents:integer('commission_cents').notNull().default(0),taxCents:integer('tax_cents').notNull().default(0),costCents:integer('cost_cents').notNull().default(0),costEstimated:integer('cost_estimated').notNull().default(0),vatIssued:integer('vat_issued').notNull().default(0),unitPrice:real('unit_price').notNull().default(0),totalPrice:real('total_price').notNull().default(0),customerName:text('customer_name').notNull().default(''),customerPhone:text('customer_phone').notNull().default(''),platform:text('platform').notNull().default(''),soldAt:text('sold_at'),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('inventory_sales_item').on(t.itemId),index('inventory_sales_created').on(t.createdAt),index('inventory_sales_seller').on(t.seller),uniqueIndex('inventory_sales_lead').on(t.leadId)]);
export const inventoryCountLines=sqliteTable('inventory_count_lines',{id:text('id').primaryKey(),countId:text('count_id').notNull(),itemId:text('item_id').notNull(),expectedQty:integer('expected_qty').notNull().default(0),countedQty:integer('counted_qty'),note:text('note').notNull().default('')},t=>[index('inventory_count_lines_count').on(t.countId),uniqueIndex('inventory_count_lines_unique').on(t.countId,t.itemId)]);

export const inventoryRequests=sqliteTable('inventory_requests',{id:text('id').primaryKey(),action:text('action').notNull(),payload:text('payload').notNull(),response:text('response').notNull(),createdAt:text('created_at').notNull()});
export const inventoryChannels=sqliteTable('inventory_channels',{name:text('name').primaryKey(),commissionRate:real('commission_rate').notNull().default(0),account:text('account').notNull().default('')});
// Хүргэлтийн журнал: Excel-ийн "ХҮРГЭЛТ" хуудсыг систем болгосон. courier_email/entered_by_email нь
// CRM гишүүнтэй холбоно, харин Excel-ээс импортлосон хуучин мөрүүдэд и-мэйл байхгүй тул нэрийг
// (courier_name) үргэлж хөтөлж, тайланг нэрээр нь бүлэглэдэг. sale_id/lead_id нь сонголттой холбоос.
export const deliveries=sqliteTable('deliveries',{id:text('id').primaryKey(),deliveredOn:text('delivered_on').notNull(),kind:text('kind').notNull().default(''),itemInfo:text('item_info').notNull().default(''),customerPhone:text('customer_phone').notNull().default(''),address:text('address').notNull().default(''),paymentChannel:text('payment_channel').notNull().default(''),contents:text('contents').notNull().default(''),courierEmail:text('courier_email'),courierName:text('courier_name').notNull(),enteredByEmail:text('entered_by_email'),enteredByName:text('entered_by_name').notNull().default(''),status:text('status').notNull().default('pending'),itemId:text('item_id'),saleId:text('sale_id'),leadId:text('lead_id'),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('deliveries_day').on(t.deliveredOn),index('deliveries_courier').on(t.courierName,t.deliveredOn),index('deliveries_status').on(t.status),index('deliveries_phone').on(t.customerPhone),index('deliveries_item').on(t.itemId)]);
// Ажлын хуваарь: Excel-ийн "Ажиллах хуваарь" хуудсыг систем болгосон. Нүд тус бүр = нэг ажилтны нэг
// өдрийн томилгоо (салбар, Хүргэлт, Тооллого эсвэл Амралт/Чөлөө). member_email нь CRM гишүүнтэй холбоно;
// хуваарьт байгаа ч системд бүртгэлгүй хүн байж болох тул person_name-ийг үргэлж хөтөлж, түүнээр бүлэглэнэ.
export const workShifts=sqliteTable('work_shifts',{id:text('id').primaryKey(),day:text('day').notNull(),memberEmail:text('member_email'),personName:text('person_name').notNull(),assignment:text('assignment').notNull(),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[uniqueIndex('work_shifts_day_person').on(t.day,t.personName),index('work_shifts_day').on(t.day,t.assignment),index('work_shifts_person').on(t.personName,t.day)]);
// Чөлөө авах / өдөр шилжүүлэх хүсэлт. Ажилтан гаргаж, Ахлах/Удирдлага/Админ шийдвэрлэнэ; батлагдмагц
// work_shifts дээр өөрчлөлт бичигдэнэ (шилжүүлэлтэд from_day чөлөөлж, to_day-д томилгоог зөөнө).
export const shiftRequests=sqliteTable('shift_requests',{id:text('id').primaryKey(),kind:text('kind').notNull(),personName:text('person_name').notNull(),memberEmail:text('member_email'),fromDay:text('from_day').notNull(),toDay:text('to_day'),assignment:text('assignment').notNull().default(''),reason:text('reason').notNull().default(''),status:text('status').notNull().default('pending'),requestedBy:text('requested_by').notNull(),decidedBy:text('decided_by'),decidedAt:text('decided_at'),decisionNote:text('decision_note').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('shift_requests_status').on(t.status,t.fromDay),index('shift_requests_person').on(t.personName,t.createdAt)]);
// Гарсан нэгж бүрийн танигдах дугаар: сериал (IMEI) эсвэл сериалгүй бараанд баркод. Нэг барааны мөр дор
// олон нэгж байж болох тул (1,224 нэгж 113 мөрөнд) дугаарыг барааны карт дээр биш, гарсан үйлдэл дээр
// хөтөлнө. source/ref_id нь хүргэлт, агуулахын борлуулалт, зээлийн худалдан авалтын аль нэгийг заана.
export const inventoryUnits=sqliteTable('inventory_units',{id:text('id').primaryKey(),itemId:text('item_id').notNull(),serial:text('serial').notNull().default(''),barcode:text('barcode').notNull().default(''),source:text('source').notNull(),refId:text('ref_id').notNull(),leadId:text('lead_id'),customerPhone:text('customer_phone').notNull().default(''),note:text('note').notNull().default(''),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('inventory_units_serial').on(t.serial),index('inventory_units_barcode').on(t.barcode),index('inventory_units_item').on(t.itemId),index('inventory_units_ref').on(t.source,t.refId),index('inventory_units_lead').on(t.leadId)]);

export const inventoryBulkEdits=sqliteTable('inventory_bulk_edits',{id:text('id').primaryKey(),actor:text('actor').notNull(),changes:text('changes').notNull(),createdAt:text('created_at').notNull()});
