import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {randomBytes} from 'node:crypto';
import {encode} from 'next-auth/jwt';
import {createClient} from '@libsql/client';
import assert from 'node:assert/strict';

// Local disposable fixtures only; production credentials and customer data are never used.
const dir=await mkdtemp(join(tmpdir(),'antmall-ux-'));
const out=resolve('docs/ux-fixes-2026-09-18');
await mkdir(out,{recursive:true});
const base='http://127.0.0.1:34672',secret=randomBytes(32).toString('base64');
const env={...process.env,AUTH_SECRET:secret,AUTH_URL:base,AUTH_TRUST_HOST:'true',AUTH_GOOGLE_ID:'ux-test',AUTH_GOOGLE_SECRET:'ux-test',CRM_OWNER_EMAIL:'owner@example.test',TURSO_DATABASE_URL:'file:'+join(dir,'test.db'),TURSO_AUTH_TOKEN:'',ANTMALL_SMS_API_KEY:'',CRM_GOOGLE_SERVICE_ACCOUNT_JSON:'',NEXT_TELEMETRY_DISABLED:'1'};
delete env.VERCEL;
execFileSync(process.execPath,['scripts/migrate.mjs'],{env,stdio:'pipe'});
console.log('Temporary database migrated');
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','34672'],{env,stdio:'ignore',windowsHide:true});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
let chrome,ws,db;
const evidence={screens:[],checks:{},errors:[]};
try{
 for(let i=0;i<80;i++){try{await fetch(base+'/login',{signal:AbortSignal.timeout(2000)});break;}catch{await pause(150);}}
 console.log('Local server ready');
 const token=await encode({secret,salt:'authjs.session-token',token:{sub:'google:owner',email:'owner@example.test',name:'Туршилтын админ'},maxAge:3600});
 const r=await fetch(base+'/api/crm',{headers:{cookie:'authjs.session-token='+token},signal:AbortSignal.timeout(10000)});
 if(!r.ok)throw new Error('Local fixture bootstrap failed: '+r.status);
 console.log('Local owner bootstrapped');
 db=createClient({url:env.TURSO_DATABASE_URL});
 const now=new Date().toISOString();
 for(const [email,name,role] of [['agent@example.test','Борлуулалтын ажилтан','agent'],['marketing@example.test','Маркетингийн ажилтан','marketing'],['it@example.test','IT ажилтан','it']])await db.execute({sql:'INSERT INTO members(email,name,role,active,last_seen) VALUES(?,?,?,1,?)',args:[email,name,role,now]});
 await db.execute("INSERT INTO app_settings(key,value,updated_at) VALUES('notification_sound','none',datetime('now')) ON CONFLICT(key) DO UPDATE SET value='none'");
 const statuses=['new','contacted','materials','pending','appointment','unreachable','won','lost','review'];
 for(let i=0;i<18;i++)await db.execute({sql:'INSERT INTO leads(id,name,phone,product,source,owner,status,next_at,next_action,created_at,updated_at,op) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',args:['ux-'+i,['Туршилтын харилцагч Бат','Туршилтын харилцагч Саруул','Урт нэртэй туршилтын байгууллага ХХК'][i%3],String(99000000+i),'Dell Pro 14 — зөөврийн компьютер','Facebook',i%3?'owner@example.test':'agent@example.test',statuses[i%9],new Date(Date.now()+(i<6?-3600000:3600000)).toISOString(),'Зээлийн нөхцөл тайлбарлаж, материал бүрдүүлэх',now,now,'ux-op-'+i]});
 for(let i=0;i<4;i++){
 await db.execute({sql:'INSERT INTO marketing_tasks(id,title,channel,budget,owner,status,due_at,note,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',args:['ux-m-'+i,'Туршилт: намрын бүтээгдэхүүний сурталчилгаа '+(i+1),'Facebook',500000+i*100000,'marketing@example.test','planned',now,'Туршилтын өгөгдөл','owner@example.test',now,now]});
 await db.execute({sql:'INSERT INTO it_tasks(id,title,system_area,owner,status,due_at,note,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',args:['ux-it-'+i,'Туршилт: сайтын сайжруулалт '+(i+1),'Вэбсайт','it@example.test','planned',now,'Туршилтын өгөгдөл','owner@example.test',now,now]});
 }
 console.log('Fixtures populated');
 chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=9333','--user-data-dir='+join(dir,'chrome'),'about:blank'],{stdio:'ignore',windowsHide:true});
 let target;
 for(let i=0;i<40;i++){try{target=(await (await fetch('http://127.0.0.1:9333/json',{signal:AbortSignal.timeout(500)})).json()).find(t=>t.type==='page');if(target)break;}catch{}await pause(150);}
 if(!target)throw new Error('Headless Chrome did not start');
 ws=new WebSocket(target.webSocketDebuggerUrl);
 await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let seq=0,dialogAnswer=false;const pending=new Map();
 evidence.checks.dialogs=[];
 ws.onmessage=event=>{const v=JSON.parse(event.data);if(v.id){const p=pending.get(v.id);if(p){pending.delete(v.id);v.error?p.reject(new Error(v.error.message)):p.resolve(v.result);}}else if(v.method==='Runtime.exceptionThrown')evidence.errors.push(v.params.exceptionDetails.exception?.description||v.params.exceptionDetails.text);else if(v.method==='Page.javascriptDialogOpening'){evidence.checks.dialogs.push({type:v.params.type,accepted:dialogAnswer});void cdp('Page.handleJavaScriptDialog',{accept:dialogAnswer});}};
 const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},20000);pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v);},reject:e=>{clearTimeout(timer);reject(e);}});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const v=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(v.exceptionDetails)throw new Error(v.exceptionDetails.text+': '+v.result.description);return v.result.value;};
 const click=async(text,selector='button')=>{const pos=await evaluate(`(()=>{const e=[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>e.textContent.trim()===${JSON.stringify(text)}||[...e.querySelectorAll('span')].some(s=>s.textContent===${JSON.stringify(text)}));if(!e)return null;e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);if(!pos)throw new Error('Missing button: '+text);await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...pos});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...pos});await pause(650);};
 const viewport=async(width,height=1000)=>{await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await pause(250);};
 const snap=async name=>{
  await pause(250);
  const metrics=await evaluate(`(()=>{const visible=e=>!!(e.getClientRects().length);const box=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {text:e.textContent.trim().slice(0,90),x:r.x,y:r.y,width:r.width,height:r.height,font:s.fontSize,color:s.color,background:s.backgroundColor,display:s.display,flexDirection:s.flexDirection}};return {url:location.href,viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,headings:[...document.querySelectorAll('h1,h2')].filter(visible).map(e=>e.textContent),primary:[...document.querySelectorAll('button.primary')].filter(visible).slice(0,5).map(box),smallText:[...document.querySelectorAll('th,small,.muted,.form-help')].filter(visible).slice(0,15).map(box),tabs:[...document.querySelectorAll('[role=tablist]')].filter(visible).map(box),chat:[...document.querySelectorAll('.chat-layout,.chat-list,.chat-thread,.chat-composer')].filter(visible).map(box),calendarMore:[...document.querySelectorAll('.month-cal-more')].map(e=>({text:e.textContent,tag:e.tagName,tabIndex:e.tabIndex})),smallTargets:[...document.querySelectorAll('button,a,input,select')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.width<24||r.height<24}).slice(0,12).map(box)}})()`);
  const shot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
  await writeFile(join(out,name+'.png'),Buffer.from(shot.data,'base64'));
  evidence.screens.push({name,...metrics});console.log('Captured '+name);
 };
 await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Network.enable');
 await viewport(1440,1000);
 await cdp('Network.setCookie',{name:'authjs.session-token',value:token,url:base,httpOnly:true,sameSite:'Lax'});
 await cdp('Page.navigate',{url:base});await pause(1800);
 const writeProbe=await evaluate("fetch('/api/sms-rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',status:'new',message:'Туршилтын SMS',enabled:false})}).then(r=>r.json())");
 assert.equal(writeProbe.ok,true,JSON.stringify(writeProbe));
 await snap('01-initial-desktop');
 evidence.checks.approvalPosition=await evaluate("document.querySelector('.dashboard-approvals').getBoundingClientRect().top");
 assert.ok(evidence.checks.approvalPosition<800,'Approvals must be visible before the metric cards');
 await click('Өнөөдрийн ажил','.nav-button');await snap('01b-today-desktop');
 await click('Борлуулалт','.nav-button');await snap('02-sales-desktop');
 await click('Календарь');await snap('03-calendar-desktop');
 await evaluate("document.querySelector('.month-cal').scrollIntoView({block:'start'})");await snap('03b-calendar-content');
 await evaluate("document.querySelector('.month-cal-more').click()");await pause(500);
 evidence.checks.fullCalendarDay=await evaluate("document.querySelectorAll('[role=dialog] .day-agenda button').length");
 assert.equal(evidence.checks.fullCalendarDay,18,'Full day must include all 18 fixtures');
 await snap('03c-calendar-day');
 await evaluate("document.querySelector('[data-slot=dialog-close]').click()");await pause(200);
 await click('Жагсаалт');
 await evaluate("document.querySelector('.lead-link').click()");await pause(600);await snap('04-lead-detail');
 await evaluate("history.back()");await pause(500);assert.equal(await evaluate("document.querySelectorAll('.detail-sheet').length"),0);
 await evaluate("history.forward()");await pause(500);assert.ok(await evaluate("!!document.querySelector('.detail-sheet')"));
 await click('Мэдээлэл');
 await snap('04b-lead-edit');
 evidence.checks.editableFields=await evaluate("[...document.querySelectorAll('[role=dialog] input')].map(e=>({name:e.name,value:e.value,readOnly:e.readOnly}))");
 const originalName=await evaluate("document.querySelector('input[name=name]').value");
 const fill=async(selector,value)=>{await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});const proto=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);await pause(100);};
 await fill('input[name=name]','Өөрчилсөн ноорог');
 await evaluate("document.querySelector('[data-slot=sheet-content] button.absolute').click()");await pause(200);
 assert.equal(await evaluate("document.querySelector('input[name=name]')?.value"),'Өөрчилсөн ноорог','Cancel closing sheet must preserve draft');
 await click('Холбоо барилт','[role=tab]');
 assert.equal(await evaluate("document.querySelector('input[name=name]')?.value"),'Өөрчилсөн ноорог','Cancel tab navigation must keep draft');
 dialogAnswer=true;await click('Холбоо барилт','[role=tab]');dialogAnswer=false;
 assert.equal(await evaluate("document.querySelector('[role=tab][data-state=active]').textContent"),'Холбоо барилт');
 await click('Мэдээлэл','[role=tab]');assert.equal(await evaluate("document.querySelector('input[name=name]').value"),originalName);
 await fill('input[name=name]','');await click('Хүсэлт хадгалах');
 assert.ok(await evaluate("!!document.querySelector('.field-error')"),'Invalid field must show inline error');
 await fill('input[name=name]',originalName);
 await evaluate("document.querySelector('[data-slot=sheet-content] [data-slot=sheet-close], [data-slot=sheet-content] button.absolute')?.click()");await pause(300);
 await click('Хяналтын самбар','.nav-button');await snap('05-dashboard-desktop');
 await click('Маркетинг','.nav-button');await snap('06-marketing-desktop');
 await cdp('Network.setBlockedURLs',{urls:['*api/marketing?report*']});await click('Тайлан','.view-toggle button');
 assert.ok(await evaluate("!!document.querySelector('.error-box')"));assert.equal(await evaluate("document.querySelectorAll('.bar-row').length"),0);await snap('06b-marketing-report-error');
 await cdp('Network.setBlockedURLs',{urls:[]});await click('Дахин оролдох');assert.ok(await evaluate("document.querySelectorAll('.bar-row').length>0"));
 await click('IT','.nav-button');await snap('07-it-desktop');
 await cdp('Network.setBlockedURLs',{urls:['*api/it?report*']});await click('Тайлан','.view-toggle button');assert.ok(await evaluate("!!document.querySelector('.error-box')"));
 await cdp('Network.setBlockedURLs',{urls:[]});await click('Дахин оролдох');assert.ok(await evaluate("document.querySelectorAll('.bar-row').length>0"));
 await click('Тохиргоо','.nav-button');await snap('08-settings-desktop');
 await evaluate("document.querySelector('[role=tab][data-state=active]').focus()");
 for(const key of ['ArrowRight','Enter']){await cdp('Input.dispatchKeyEvent',{type:'keyDown',key,code:key,windowsVirtualKeyCode:key==='Enter'?13:39});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key,code:key});await pause(120);}await pause(200);
 assert.equal(await evaluate("document.querySelector('[role=tab][data-state=active]').textContent"),'Системийн тохиргоо');await click('Профайл','[role=tab]');evidence.checks.keyboardTabs=true;
 await click('Google Sheets','[role=tab]');await snap('08b-sheets');
 assert.ok(await evaluate("[...document.querySelectorAll('.setup-steps a')].every(a=>document.querySelector(a.getAttribute('href')))"),'Every setup step must have a destination');
 await cdp('Network.setBlockedURLs',{urls:['*api/sms-rules*']});
 await click('SMS тохиргоо','[role=tab]');await snap('08c-sms-error');
 evidence.checks.smsBlocked=await evaluate("({text:document.querySelector('.sheet-settings').innerText,alerts:[...document.querySelectorAll('[role=alert]')].map(e=>e.textContent)})");
 await cdp('Network.setBlockedURLs',{urls:[]});
 await click('Дахин оролдох');assert.ok(await evaluate("!!document.querySelector('.sms-rule-add')"),'SMS error must recover');
 const seededRule=await evaluate("fetch('/api/sms-rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',status:'new',message:'Туршилтын SMS',enabled:false})}).then(r=>r.json())");
 assert.equal(seededRule.ok,true,JSON.stringify(seededRule));
 await click('Профайл','[role=tab]');await click('SMS тохиргоо','[role=tab]');
 await evaluate("document.querySelector('.sms-rule-row [role=switch]').click()");await fill('.sms-rule-row textarea','Шинэ мессеж');
 const unsavedRule=await evaluate("fetch('/api/sms-rules').then(r=>r.json()).then(d=>d.items.find(r=>r.status==='new'))");
 assert.equal(unsavedRule.enabled,0);assert.equal(unsavedRule.message,'Туршилтын SMS');
 await click('Хадгалах','.sms-rule-row button');
 const savedRule=await evaluate("fetch('/api/sms-rules').then(r=>r.json()).then(d=>d.items.find(r=>r.status==='new'))");
 assert.equal(savedRule.enabled,1);assert.equal(savedRule.message,'Шинэ мессеж');
 const ruleCount=await evaluate("document.querySelectorAll('.sms-rule-row').length");
 await evaluate("document.querySelector('.sms-rule-row button[aria-label$=\"устгах\"]').click()");await pause(150);
 await click('Цуцлах','[role=dialog] button');
 assert.equal(await evaluate("document.querySelectorAll('.sms-rule-row').length"),ruleCount);
 await evaluate("document.querySelector('.sms-rule-row button[aria-label$=\"устгах\"]').click()");await pause(150);
 await click('Тийм, дүрмийг устгах');assert.equal(await evaluate("document.querySelectorAll('.sms-rule-row').length"),ruleCount-1);
 evidence.checks.smsExplicitSaveAndDelete=true;
 await click('Профайл','[role=tab]');
 await click('Ажилтны чат','.nav-button');await snap('09-chat-desktop');
 await viewport(390,844);await snap('10-chat-mobile');
 await click('Борлуулалтын ажилтан','.chat-peer');
 await fill('.chat-composer input:not([type=file])','Эхний харилцагчийн ноорог');
 await evaluate("document.querySelector('.chat-back').click()");await pause(200);
 await click('Маркетингийн ажилтан','.chat-peer');
 assert.equal(await evaluate("document.querySelector('.chat-composer input:not([type=file])').value"),'','Draft must not leak to another peer');
 await evaluate("document.querySelector('.chat-back').click()");await pause(200);
 await click('Борлуулалтын ажилтан','.chat-peer');
 assert.equal(await evaluate("document.querySelector('.chat-composer input:not([type=file])').value"),'Эхний харилцагчийн ноорог');
 await snap('10b-chat-thread-mobile');
 await fill('.chat-composer input:not([type=file])','');
 await evaluate("document.querySelector('[data-slot=sheet-content] button.absolute')?.click()");await pause(400);
 // Navigate using the real navigation controls after opening the mobile sidebar.
 const navMobile=async label=>{await evaluate("document.querySelector('[data-slot=sidebar-trigger]').click()");await pause(300);await click(label,'.nav-button');await evaluate("document.querySelector('[data-mobile=true] button.absolute')?.click()");await pause(350);};
 await navMobile('Борлуулалт');await snap('11-sales-mobile');
 await evaluate("document.querySelector('.lead-list-table').scrollIntoView({block:'start'})");await snap('11b-sales-cards-mobile');
 await viewport(360,800);await snap('11c-sales-360');await viewport(390,844);
 await click('Календарь');await snap('12-calendar-mobile');
 await evaluate("document.querySelector('.month-cal').scrollIntoView({block:'start'})");await snap('12b-calendar-content-mobile');
 await viewport(320,740);await snap('13-calendar-320');
 await viewport(390,844);await navMobile('Тохиргоо');await snap('14-settings-mobile');
 await viewport(320,740);await snap('14b-settings-320');
 await viewport(768,1000);await snap('14c-settings-768');
 await viewport(1440,1000);await click('Борлуулалт','.nav-button');
 await fill('input[aria-label="Хүсэлт хайх"]','Туршилтын');await pause(400);
 evidence.checks.beforeReload=await evaluate("({url:location.href,title:document.querySelector('h1').textContent})");
 await cdp('Page.reload');await pause(1400);
 evidence.checks.afterReload=await evaluate("({url:location.href,title:document.querySelector('h1').textContent})");
 assert.equal(evidence.checks.beforeReload.url,evidence.checks.afterReload.url);
 assert.equal(evidence.checks.beforeReload.title,evidence.checks.afterReload.title);
 await evaluate("fetch('/api/crm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id:'ux-17',version:1,data:{note:'Local restore test'}})}).then(r=>r.json())");
 await click('Устгасан хүсэлт');await click('Сэргээх','[role=dialog] button');await fill('textarea[name=note]','Андуурсан устгал сэргээв');await snap('14e-restore-confirmation');await click('Сэргээх','[role=dialog] button.primary');
 const restored=await evaluate("fetch('/api/crm?id=ux-17').then(r=>r.json())");assert.equal(restored.lead.status,'review');assert.ok(restored.activities.some(a=>a.kind==='restore'));
 await evaluate("document.querySelector('[data-slot=dialog-close]').click()");await pause(200);
 evidence.checks.restoreUI=true;
 await click('Хяналтын самбар','.nav-button');await viewport(1280,1000);await snap('14d-dashboard-1280');
 await cdp('Network.clearBrowserCookies');await cdp('Page.navigate',{url:base+'/login'});await pause(700);await snap('15-login');
 await writeFile(join(out,'evidence.json'),JSON.stringify(evidence,null,2));
 assert.equal(evidence.errors.length,0,'No runtime/hydration exceptions');
 for(const screen of evidence.screens)assert.ok(screen.scrollWidth<=screen.viewport,screen.name+' has horizontal overflow');
 console.log('Audit evidence saved: '+out);
}finally{
 await writeFile(join(out,'evidence.json'),JSON.stringify(evidence,null,2));
 ws?.close();chrome?.kill();server.kill();db?.close();
}
